#!/usr/bin/env bash
# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version. See <https://www.gnu.org/licenses/>.
#
# Machine-readable verification evidence. This script derives, from the source
# tree alone (no build required), a canonical JSON inventory of what NONOS
# proves and with which tools: the Lean specification corpus, the functions
# mechanically extracted from real MIR by Charon and Aeneas, the Verus and Kani
# harnesses, and the runnable proof crates, plus the pinned toolchains and the
# axiom policy. It is deterministic: run twice on the same tree and the bytes
# match. CI regenerates it and diffs against the committed verification/EVIDENCE.json,
# so the file in the repo is always an accurate, CI-checked statement of the
# verification surface. The green Lean, Verus, Kani and extraction jobs are the
# proof that the surface actually checks; this file is the inventory of it.
#
# Run from the repository root.

set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

case "$(uname -s)" in
  Darwin) SHA256="shasum -a 256" ;;
  *)      SHA256="sha256sum" ;;
esac
sha() { $SHA256 "$1" | cut -d' ' -f1; }

lean_dir="verification/lean/Nonos"

# --- Lean specification corpus (core-only, no Mathlib) ---
lean_modules=$(find "$lean_dir" -name '*.lean' | wc -l | tr -d ' ')
lean_theorems=$(grep -rh '^theorem ' "$lean_dir" 2>/dev/null | wc -l | tr -d ' ')
# A real sorry (not the word in a comment) anywhere is a hard failure.
lean_sorry=$(grep -rn 'sorry' "$lean_dir" 2>/dev/null \
  | grep -v 'no sorry anywhere' | grep -vcE ':[[:space:]]*--' || true)
lean_toolchain=$(cat verification/lean/lean-toolchain 2>/dev/null | tr -d '[:space:]')
axiom_profiled=$(grep -c '^#print axioms' verification/lean/AxiomProfile.lean 2>/dev/null || echo 0)

# --- Mechanically extracted functions (Charon + Aeneas, from real MIR) ---
# The extraction start points are the source of truth in the CI workflow.
extracted_starts=$(grep -oE "start-from '[^']+'" .github/workflows/verify.yml 2>/dev/null \
  | sed "s/start-from '//;s/'//" | LC_ALL=C sort)
extracted_json=$(printf '%s\n' "$extracted_starts" | grep -v '^$' \
  | jq -R . | jq -s .)
# The generated Lean files that carry the extraction, with their hashes.
extracted_files_json=$(
  { grep -rl 'GENERATED BY AENEAS' verification/extraction/lean/NonosExtraction \
      verification/extraction/lean/Policy 2>/dev/null || true; } \
  | LC_ALL=C sort \
  | while IFS= read -r f; do
      [ -n "$f" ] && printf '{"path":"%s","sha256":"%s"}\n' "$f" "$(sha "$f")"
    done | jq -s .
)

# --- Other proof systems ---
verus_files=$(find verification/verus -name '*.rs' 2>/dev/null | wc -l | tr -d ' ')
# Source only. A build tree carries the same string inside its artifacts, so
# counting those inflates the figure and makes this walk minutes long on a
# machine that has actually built something.
kani_harnesses=$(grep -rh --include='*.rs' --exclude-dir=target \
  '#\[kani::proof\]' userland 2>/dev/null | wc -l | tr -d ' ')
runnable_crates=$(ls -d userland/*_proofs 2>/dev/null | wc -l | tr -d ' ')

rust_toolchain=$(grep -oE 'channel = "[^"]+"' rust-toolchain.toml 2>/dev/null \
  | head -1 | sed 's/channel = "//;s/"//' || echo unknown)

jq -Sn \
  --arg schema "nonos-verification-evidence/v1" \
  --argjson lean_modules "$lean_modules" \
  --argjson lean_theorems "$lean_theorems" \
  --argjson lean_sorry "$lean_sorry" \
  --arg lean_toolchain "$lean_toolchain" \
  --argjson axiom_profiled "$axiom_profiled" \
  --argjson extracted "$extracted_json" \
  --argjson extracted_files "$extracted_files_json" \
  --argjson verus_files "$verus_files" \
  --argjson kani_harnesses "$kani_harnesses" \
  --argjson runnable_crates "$runnable_crates" \
  --arg rust_toolchain "$rust_toolchain" \
  '{
    schema: $schema,
    axiom_policy: {
      allowed: ["propext", "Classical.choice", "Quot.sound"],
      forbidden: ["sorryAx"],
      note: "Every profiled Lean theorem depends on at most the three standard axioms; a sorry would surface as sorryAx and fail CI."
    },
    proof_systems: {
      lean_specification: {
        modules: $lean_modules,
        theorems: $lean_theorems,
        sorry_count: $lean_sorry,
        axiom_profiled_theorems: $axiom_profiled,
        toolchain: $lean_toolchain,
        mathlib: false
      },
      lean_extraction: {
        description: "Functions lowered from real Rust MIR by Charon and translated to Lean by Aeneas, then proven on the extracted definition.",
        extracted_functions: $extracted,
        generated_files: $extracted_files
      },
      verus: { source_files: $verus_files },
      kani: { harnesses: $kani_harnesses },
      runnable: { proof_crates: $runnable_crates }
    },
    toolchains: {
      lean: $lean_toolchain,
      rust_kernel: $rust_toolchain
    }
  }'
