[package]
name = "nonos_capsule_image_codec"
version = "0.3.0"
edition = "2021"
publish = false
license = "AGPL-3.0"
authors = ["eK@nonos.systems"]
description = "NONOS image codec capsule"

[[bin]]
name = "image_codec"
path = "src/main.rs"

[dependencies]
nonos_libc = { package = "nonos_userland_libc", path = "../libc" }
nonos_toolkit = { package = "nonos_toolkit", path = "../toolkit" }

[profile.release]
panic = "abort"
opt-level = 2
lto = false
debug = false
strip = true

[profile.dev]
panic = "abort"
opt-level = 0
debug = true
