# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# jsonxf: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := jsonxf
CAPSULE_HANDLE             := jsonxf
CAPSULE_DIR                := userland/capsule_jsonxf
CAPSULE_BIN_NAME           := jsonxf
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.jsonxf
CAPSULE_SERVICE_ENDPOINT   := service:4906:tool.jsonxf
CAPSULE_REPLY_ENDPOINT     := reply:4907:endpoint.tool.jsonxf.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-jsonxf/bin/jsonxf
CAPSULE_METADATA           := crates.io jsonxf publisher

include nonos-mk/capsule.mk
