# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# csview: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := csview
CAPSULE_HANDLE             := csview
CAPSULE_DIR                := userland/capsule_csview
CAPSULE_BIN_NAME           := csview
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.csview
CAPSULE_SERVICE_ENDPOINT   := service:4914:tool.csview
CAPSULE_REPLY_ENDPOINT     := reply:4915:endpoint.tool.csview.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-csview/bin/csview
CAPSULE_METADATA           := crates.io csview publisher

include nonos-mk/capsule.mk
