# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# huniq: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := huniq
CAPSULE_HANDLE             := huniq
CAPSULE_DIR                := userland/capsule_huniq
CAPSULE_BIN_NAME           := huniq
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.huniq
CAPSULE_SERVICE_ENDPOINT   := service:4912:tool.huniq
CAPSULE_REPLY_ENDPOINT     := reply:4913:endpoint.tool.huniq.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-huniq/bin/huniq
CAPSULE_METADATA           := crates.io huniq publisher

include nonos-mk/capsule.mk
