# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# pastel: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := pastel
CAPSULE_HANDLE             := pastel
CAPSULE_DIR                := userland/capsule_pastel
CAPSULE_BIN_NAME           := pastel
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.pastel
CAPSULE_SERVICE_ENDPOINT   := service:4904:tool.pastel
CAPSULE_REPLY_ENDPOINT     := reply:4905:endpoint.tool.pastel.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-pastel/bin/pastel
CAPSULE_METADATA           := crates.io pastel publisher

include nonos-mk/capsule.mk
