# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# dotenv-linter: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := dotenv-linter
CAPSULE_HANDLE             := dotenv-linter
CAPSULE_DIR                := userland/capsule_dotenv-linter
CAPSULE_BIN_NAME           := dotenv-linter
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.dotenv-linter
CAPSULE_SERVICE_ENDPOINT   := service:4902:tool.dotenv-linter
CAPSULE_REPLY_ENDPOINT     := reply:4903:endpoint.tool.dotenv-linter.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-dotenv-linter/bin/dotenv-linter
CAPSULE_METADATA           := crates.io dotenv-linter publisher

include nonos-mk/capsule.mk
