# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# tokei: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := tokei
CAPSULE_HANDLE             := tokei
CAPSULE_DIR                := userland/capsule_tokei
CAPSULE_BIN_NAME           := tokei
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.tokei
CAPSULE_SERVICE_ENDPOINT   := service:4910:tool.tokei
CAPSULE_REPLY_ENDPOINT     := reply:4911:endpoint.tool.tokei.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-tokei/bin/tokei
CAPSULE_METADATA           := crates.io tokei publisher

include nonos-mk/capsule.mk
