// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

pub mod audit;
pub mod bits;
pub mod chain;
pub mod delegation;
pub mod fixtures;
pub mod multisig;
pub mod resource;
pub mod token;
pub mod types;

use crate::test::framework::{TestCase, TestSuite};

/// Run all capabilities subsystem tests.
/// Returns true if all tests pass, false otherwise.
pub fn run_all() -> bool {
    let mut suite = TestSuite::new("Capabilities");

    // Audit tests (36 tests)
    suite.add(TestCase::new(
        "audit_entry_in_time_range_true",
        audit::test_audit_entry_in_time_range_true,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_in_time_range_false",
        audit::test_audit_entry_in_time_range_false,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_module_true",
        audit::test_audit_entry_matches_module_true,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_module_false",
        audit::test_audit_entry_matches_module_false,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_action_true",
        audit::test_audit_entry_matches_action_true,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_action_false",
        audit::test_audit_entry_matches_action_false,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_capability_true",
        audit::test_audit_entry_matches_capability_true,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_capability_false",
        audit::test_audit_entry_matches_capability_false,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_matches_capability_none",
        audit::test_audit_entry_matches_capability_none,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_display_success",
        audit::test_audit_entry_display_success,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_entry_display_failure",
        audit::test_audit_entry_display_failure,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_success_rate_all_success",
        audit::test_audit_stats_snapshot_success_rate_all_success,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_success_rate_half",
        audit::test_audit_stats_snapshot_success_rate_half,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_success_rate_zero_logged",
        audit::test_audit_stats_snapshot_success_rate_zero_logged,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_failure_rate",
        audit::test_audit_stats_snapshot_failure_rate,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_failure_rate_zero_logged",
        audit::test_audit_stats_snapshot_failure_rate_zero_logged,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_buffer_usage_percent",
        audit::test_audit_stats_snapshot_buffer_usage_percent,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_buffer_usage_percent_zero_capacity",
        audit::test_audit_stats_snapshot_buffer_usage_percent_zero_capacity,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_display",
        audit::test_audit_stats_snapshot_display,
        "capabilities/audit",
    ));
    suite.add(TestCase::new(
        "audit_stats_snapshot_default",
        audit::test_audit_stats_snapshot_default,
        "capabilities/audit",
    ));
    suite.add(TestCase::new("audit_capacity", audit::test_audit_capacity, "capabilities/audit"));
    suite.add(TestCase::new(
        "max_log_entries_constant",
        audit::test_max_log_entries_constant,
        "capabilities/audit",
    ));
    suite.add(TestCase::new("clear_log", audit::test_clear_log, "capabilities/audit"));
    suite.add(TestCase::new("log_raw", audit::test_log_raw, "capabilities/audit"));
    suite.add(TestCase::new(
        "log_use_with_token",
        audit::test_log_use_with_token,
        "capabilities/audit",
    ));
    suite.add(TestCase::new("log_success", audit::test_log_success, "capabilities/audit"));
    suite.add(TestCase::new("log_failure", audit::test_log_failure, "capabilities/audit"));
    suite.add(TestCase::new(
        "get_log_returns_entries",
        audit::test_get_log_returns_entries,
        "capabilities/audit",
    ));
    suite.add(TestCase::new("get_recent", audit::test_get_recent, "capabilities/audit"));
    suite.add(TestCase::new(
        "get_recent_more_than_available",
        audit::test_get_recent_more_than_available,
        "capabilities/audit",
    ));
    suite.add(TestCase::new("get_stats", audit::test_get_stats, "capabilities/audit"));
    suite.add(TestCase::new("reset_stats", audit::test_reset_stats, "capabilities/audit"));
    suite.add(TestCase::new("get_by_module", audit::test_get_by_module, "capabilities/audit"));
    suite.add(TestCase::new("get_by_action", audit::test_get_by_action, "capabilities/audit"));
    suite.add(TestCase::new(
        "get_by_capability",
        audit::test_get_by_capability,
        "capabilities/audit",
    ));
    suite.add(TestCase::new("get_successes", audit::test_get_successes, "capabilities/audit"));
    suite.add(TestCase::new("get_failures", audit::test_get_failures, "capabilities/audit"));

    // Bits tests (26 tests)
    suite.add(TestCase::new(
        "caps_to_bits_empty",
        bits::test_caps_to_bits_empty,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "caps_to_bits_single",
        bits::test_caps_to_bits_single,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "caps_to_bits_multiple",
        bits::test_caps_to_bits_multiple,
        "capabilities/bits",
    ));
    suite.add(TestCase::new("caps_to_bits_all", bits::test_caps_to_bits_all, "capabilities/bits"));
    suite.add(TestCase::new(
        "caps_to_bits_duplicates",
        bits::test_caps_to_bits_duplicates,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "bits_to_caps_zero",
        bits::test_bits_to_caps_zero,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "bits_to_caps_single",
        bits::test_bits_to_caps_single,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "bits_to_caps_multiple",
        bits::test_bits_to_caps_multiple,
        "capabilities/bits",
    ));
    suite.add(TestCase::new("bits_to_caps_all", bits::test_bits_to_caps_all, "capabilities/bits"));
    suite.add(TestCase::new(
        "bits_to_caps_ignores_invalid_bits",
        bits::test_bits_to_caps_ignores_invalid_bits,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "roundtrip_caps_to_bits_to_caps",
        bits::test_roundtrip_caps_to_bits_to_caps,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "has_capability_true",
        bits::test_has_capability_true,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "has_capability_false",
        bits::test_has_capability_false,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "has_capability_zero_bits",
        bits::test_has_capability_zero_bits,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "add_capability_to_zero",
        bits::test_add_capability_to_zero,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "add_capability_cumulative",
        bits::test_add_capability_cumulative,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "add_capability_idempotent",
        bits::test_add_capability_idempotent,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "remove_capability_present",
        bits::test_remove_capability_present,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "remove_capability_not_present",
        bits::test_remove_capability_not_present,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "remove_capability_from_zero",
        bits::test_remove_capability_from_zero,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "remove_all_capabilities",
        bits::test_remove_all_capabilities,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "capability_count_zero",
        bits::test_capability_count_zero,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "capability_count_one",
        bits::test_capability_count_one,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "capability_count_multiple",
        bits::test_capability_count_multiple,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "capability_count_all",
        bits::test_capability_count_all,
        "capabilities/bits",
    ));
    suite.add(TestCase::new(
        "capability_count_ignores_high_bits",
        bits::test_capability_count_ignores_high_bits,
        "capabilities/bits",
    ));

    // Chain tests (44 tests)
    suite.add(TestCase::new(
        "capability_chain_new",
        chain::test_capability_chain_new,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_empty",
        chain::test_capability_chain_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_single",
        chain::test_capability_chain_single,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_push",
        chain::test_capability_chain_push,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_pop",
        chain::test_capability_chain_pop,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_pop_empty",
        chain::test_capability_chain_pop_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_root",
        chain::test_capability_chain_root,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_root_empty",
        chain::test_capability_chain_root_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_leaf",
        chain::test_capability_chain_leaf,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_leaf_empty",
        chain::test_capability_chain_leaf_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_get",
        chain::test_capability_chain_get,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_tokens",
        chain::test_capability_chain_tokens,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_final_owner",
        chain::test_capability_chain_final_owner,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_final_owner_empty",
        chain::test_capability_chain_final_owner_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_root_owner",
        chain::test_capability_chain_root_owner,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_root_owner_empty",
        chain::test_capability_chain_root_owner_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_max_depth",
        chain::test_capability_chain_max_depth,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_default",
        chain::test_capability_chain_default,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "capability_chain_display",
        chain::test_capability_chain_display,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "max_chain_depth_constant",
        chain::test_max_chain_depth_constant,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "max_chain_depth_function",
        chain::test_max_chain_depth_function,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_empty_chain_as_str",
        chain::test_chain_error_empty_chain_as_str,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_too_deep_as_str",
        chain::test_chain_error_too_deep_as_str,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_invalid_token_as_str",
        chain::test_chain_error_invalid_token_as_str,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_expired_token_as_str",
        chain::test_chain_error_expired_token_as_str,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_broken_link_as_str",
        chain::test_chain_error_broken_link_as_str,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_capability_not_found_as_str",
        chain::test_chain_error_capability_not_found_as_str,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_is_recoverable_expired",
        chain::test_chain_error_is_recoverable_expired,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_is_recoverable_cap_not_found",
        chain::test_chain_error_is_recoverable_cap_not_found,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_is_recoverable_empty",
        chain::test_chain_error_is_recoverable_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_is_recoverable_invalid",
        chain::test_chain_error_is_recoverable_invalid,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_failed_index_invalid_token",
        chain::test_chain_error_failed_index_invalid_token,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_failed_index_expired_token",
        chain::test_chain_error_failed_index_expired_token,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_failed_index_broken_link",
        chain::test_chain_error_failed_index_broken_link,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_failed_index_empty_chain",
        chain::test_chain_error_failed_index_empty_chain,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_failed_index_cap_not_found",
        chain::test_chain_error_failed_index_cap_not_found,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_display_empty_chain",
        chain::test_chain_error_display_empty_chain,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_display_too_deep",
        chain::test_chain_error_display_too_deep,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_display_invalid_token",
        chain::test_chain_error_display_invalid_token,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "chain_error_equality",
        chain::test_chain_error_equality,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "verify_chain_empty",
        chain::test_verify_chain_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "is_chain_valid_empty",
        chain::test_is_chain_valid_empty,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "effective_capabilities_empty_chain",
        chain::test_effective_capabilities_empty_chain,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "effective_capabilities_single_token",
        chain::test_effective_capabilities_single_token,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "effective_capabilities_intersection",
        chain::test_effective_capabilities_intersection,
        "capabilities/chain",
    ));
    suite.add(TestCase::new(
        "first_invalid_index_empty_chain",
        chain::test_first_invalid_index_empty_chain,
        "capabilities/chain",
    ));

    // Delegation tests (44 tests)
    suite.add(TestCase::new(
        "delegation_grants_true",
        delegation::test_delegation_grants_true,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_false",
        delegation::test_delegation_grants_false,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_capability_count",
        delegation::test_delegation_capability_count,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_capability_count_empty",
        delegation::test_delegation_capability_count_empty,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_all_true",
        delegation::test_delegation_grants_all_true,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_all_false",
        delegation::test_delegation_grants_all_false,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_all_empty",
        delegation::test_delegation_grants_all_empty,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_any_true",
        delegation::test_delegation_grants_any_true,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_any_false",
        delegation::test_delegation_grants_any_false,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_grants_any_empty",
        delegation::test_delegation_grants_any_empty,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_is_valid_no_expiry",
        delegation::test_delegation_is_valid_no_expiry,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_is_expired_no_expiry",
        delegation::test_delegation_is_expired_no_expiry,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_is_expired_future",
        delegation::test_delegation_is_expired_future,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_is_expired_past",
        delegation::test_delegation_is_expired_past,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_remaining_ms_none",
        delegation::test_delegation_remaining_ms_none,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_remaining_ms_future",
        delegation::test_delegation_remaining_ms_future,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_remaining_ms_past",
        delegation::test_delegation_remaining_ms_past,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_display",
        delegation::test_delegation_display,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_display_with_expiry",
        delegation::test_delegation_display_with_expiry,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_display_no_expiry",
        delegation::test_delegation_display_no_expiry,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_missing_signing_key_as_str",
        delegation::test_delegation_error_missing_signing_key_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_invalid_parent_token_as_str",
        delegation::test_delegation_error_invalid_parent_token_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_parent_expired_as_str",
        delegation::test_delegation_error_parent_expired_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_capability_not_held_as_str",
        delegation::test_delegation_error_capability_not_held_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_delegation_expired_as_str",
        delegation::test_delegation_error_delegation_expired_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_invalid_signature_as_str",
        delegation::test_delegation_error_invalid_signature_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_no_capabilities_as_str",
        delegation::test_delegation_error_no_capabilities_as_str,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_is_recoverable_delegation_expired",
        delegation::test_delegation_error_is_recoverable_delegation_expired,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_is_recoverable_parent_expired",
        delegation::test_delegation_error_is_recoverable_parent_expired,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_is_recoverable_invalid_signature",
        delegation::test_delegation_error_is_recoverable_invalid_signature,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_is_recoverable_missing_key",
        delegation::test_delegation_error_is_recoverable_missing_key,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_display",
        delegation::test_delegation_error_display,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_error_equality",
        delegation::test_delegation_error_equality,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_material_produces_48_bytes",
        delegation::test_delegation_material_produces_48_bytes,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_material_deterministic",
        delegation::test_delegation_material_deterministic,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_material_different_for_different_delegators",
        delegation::test_delegation_material_different_for_different_delegators,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "delegation_material_different_for_different_delegatees",
        delegation::test_delegation_material_different_for_different_delegatees,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "compute_delegation_signature_produces_64_bytes",
        delegation::test_compute_delegation_signature_produces_64_bytes,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "compute_delegation_signature_deterministic",
        delegation::test_compute_delegation_signature_deterministic,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "compute_delegation_signature_different_keys",
        delegation::test_compute_delegation_signature_different_keys,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "compute_delegation_signature_different_material",
        delegation::test_compute_delegation_signature_different_material,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "create_delegation_unchecked_empty_caps",
        delegation::test_create_delegation_unchecked_empty_caps,
        "capabilities/delegation",
    ));
    suite.add(TestCase::new(
        "verify_delegation_standalone_expired",
        delegation::test_verify_delegation_standalone_expired,
        "capabilities/delegation",
    ));

    // Multisig tests (61 tests)
    suite.add(TestCase::new(
        "max_signers_constant",
        multisig::test_max_signers_constant,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "max_threshold_constant",
        multisig::test_max_threshold_constant,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "signature_size_constant",
        multisig::test_signature_size_constant,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "max_signers_function",
        multisig::test_max_signers_function,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "max_threshold_function",
        multisig::test_max_threshold_function,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_grants_true",
        multisig::test_multisig_token_grants_true,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_grants_false",
        multisig::test_multisig_token_grants_false,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_signature_count_initial",
        multisig::test_multisig_token_signature_count_initial,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_threshold_met_false",
        multisig::test_multisig_token_threshold_met_false,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_signatures_needed",
        multisig::test_multisig_token_signatures_needed,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_has_signed_false",
        multisig::test_multisig_token_has_signed_false,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_is_authorized_true",
        multisig::test_multisig_token_is_authorized_true,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_is_authorized_false",
        multisig::test_multisig_token_is_authorized_false,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_signed_by_empty",
        multisig::test_multisig_token_signed_by_empty,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_pending_signers_all",
        multisig::test_multisig_token_pending_signers_all,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_is_expired_false",
        multisig::test_multisig_token_is_expired_false,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_remaining_ms_none",
        multisig::test_multisig_token_remaining_ms_none,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_permission_count",
        multisig::test_multisig_token_permission_count,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_signer_count",
        multisig::test_multisig_token_signer_count,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_token_display",
        multisig::test_multisig_token_display,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_no_signers_as_str",
        multisig::test_multisig_error_no_signers_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_too_many_signers_as_str",
        multisig::test_multisig_error_too_many_signers_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_threshold_exceeds_signers_as_str",
        multisig::test_multisig_error_threshold_exceeds_signers_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_zero_threshold_as_str",
        multisig::test_multisig_error_zero_threshold_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_duplicate_signer_as_str",
        multisig::test_multisig_error_duplicate_signer_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_unauthorized_signer_as_str",
        multisig::test_multisig_error_unauthorized_signer_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_threshold_not_met_as_str",
        multisig::test_multisig_error_threshold_not_met_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_token_expired_as_str",
        multisig::test_multisig_error_token_expired_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_invalid_signature_as_str",
        multisig::test_multisig_error_invalid_signature_as_str,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_is_recoverable_duplicate",
        multisig::test_multisig_error_is_recoverable_duplicate,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_is_recoverable_threshold_not_met",
        multisig::test_multisig_error_is_recoverable_threshold_not_met,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_is_recoverable_no_signers",
        multisig::test_multisig_error_is_recoverable_no_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_no_signers",
        multisig::test_multisig_error_display_no_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_too_many_signers",
        multisig::test_multisig_error_display_too_many_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_threshold_exceeds",
        multisig::test_multisig_error_display_threshold_exceeds,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_duplicate_signer",
        multisig::test_multisig_error_display_duplicate_signer,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_unauthorized",
        multisig::test_multisig_error_display_unauthorized,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_threshold_not_met",
        multisig::test_multisig_error_display_threshold_not_met,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_display_invalid_signature",
        multisig::test_multisig_error_display_invalid_signature,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "multisig_error_equality",
        multisig::test_multisig_error_equality,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "create_multisig_token_zero_threshold",
        multisig::test_create_multisig_token_zero_threshold,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "create_multisig_token_no_signers",
        multisig::test_create_multisig_token_no_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "create_multisig_token_threshold_exceeds_signers",
        multisig::test_create_multisig_token_threshold_exceeds_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "create_multisig_token_too_many_signers",
        multisig::test_create_multisig_token_too_many_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "create_multisig_token_success",
        multisig::test_create_multisig_token_success,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "create_multisig_token_with_nonce",
        multisig::test_create_multisig_token_with_nonce,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "add_signature_unauthorized",
        multisig::test_add_signature_unauthorized,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "add_signature_success",
        multisig::test_add_signature_success,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "add_signature_duplicate",
        multisig::test_add_signature_duplicate,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "remove_signature_present",
        multisig::test_remove_signature_present,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "remove_signature_not_present",
        multisig::test_remove_signature_not_present,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "clear_signatures",
        multisig::test_clear_signatures,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "signature_material_produces_40_bytes",
        multisig::test_signature_material_produces_40_bytes,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "signature_material_deterministic",
        multisig::test_signature_material_deterministic,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "signature_material_different_signers",
        multisig::test_signature_material_different_signers,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "compute_signature_produces_32_bytes",
        multisig::test_compute_signature_produces_32_bytes,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "compute_signature_deterministic",
        multisig::test_compute_signature_deterministic,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "compute_signature_different_keys",
        multisig::test_compute_signature_different_keys,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "count_valid_signatures_empty",
        multisig::test_count_valid_signatures_empty,
        "capabilities/multisig",
    ));
    suite.add(TestCase::new(
        "verify_multisig_threshold_not_met",
        multisig::test_verify_multisig_threshold_not_met,
        "capabilities/multisig",
    ));

    // Resource tests (53 tests)
    suite.add(TestCase::new(
        "resource_quota_new",
        resource::test_resource_quota_new,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_unlimited",
        resource::test_resource_quota_unlimited,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_bytes_only",
        resource::test_resource_quota_bytes_only,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_ops_only",
        resource::test_resource_quota_ops_only,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_expired_no_expiry",
        resource::test_resource_quota_is_expired_no_expiry,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_expired_future",
        resource::test_resource_quota_is_expired_future,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_expired_past",
        resource::test_resource_quota_is_expired_past,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_empty_true",
        resource::test_resource_quota_is_empty_true,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_empty_false_bytes",
        resource::test_resource_quota_is_empty_false_bytes,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_empty_false_ops",
        resource::test_resource_quota_is_empty_false_ops,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_unlimited_true",
        resource::test_resource_quota_is_unlimited_true,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_unlimited_false_bytes",
        resource::test_resource_quota_is_unlimited_false_bytes,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_unlimited_false_ops",
        resource::test_resource_quota_is_unlimited_false_ops,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_is_unlimited_false_expiry",
        resource::test_resource_quota_is_unlimited_false_expiry,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_remaining_ms_none",
        resource::test_resource_quota_remaining_ms_none,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_remaining_ms_future",
        resource::test_resource_quota_remaining_ms_future,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_remaining_ms_past",
        resource::test_resource_quota_remaining_ms_past,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_display",
        resource::test_resource_quota_display,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_display_with_expiry",
        resource::test_resource_quota_display_with_expiry,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_quota_default",
        resource::test_resource_quota_default,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_missing_signing_key_as_str",
        resource::test_resource_error_missing_signing_key_as_str,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_token_expired_as_str",
        resource::test_resource_error_token_expired_as_str,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_invalid_signature_as_str",
        resource::test_resource_error_invalid_signature_as_str,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_insufficient_bytes_as_str",
        resource::test_resource_error_insufficient_bytes_as_str,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_insufficient_ops_as_str",
        resource::test_resource_error_insufficient_ops_as_str,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_zero_quota_as_str",
        resource::test_resource_error_zero_quota_as_str,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_is_quota_error_bytes",
        resource::test_resource_error_is_quota_error_bytes,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_is_quota_error_ops",
        resource::test_resource_error_is_quota_error_ops,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_is_quota_error_false",
        resource::test_resource_error_is_quota_error_false,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_display_missing_key",
        resource::test_resource_error_display_missing_key,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_display_insufficient_bytes",
        resource::test_resource_error_display_insufficient_bytes,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_display_insufficient_ops",
        resource::test_resource_error_display_insufficient_ops,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_error_equality",
        resource::test_resource_error_equality,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "create_resource_token_zero_quota",
        resource::test_create_resource_token_zero_quota,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "create_resource_token_with_nonce_zero_quota",
        resource::test_create_resource_token_with_nonce_zero_quota,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_next_nonce_nonzero",
        resource::test_resource_next_nonce_nonzero,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_next_nonce_different",
        resource::test_resource_next_nonce_different,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_reset_nonce_counter",
        resource::test_resource_reset_nonce_counter,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_token_material_produces_40_bytes",
        resource::test_resource_token_material_produces_40_bytes,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_token_material_deterministic",
        resource::test_resource_token_material_deterministic,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_token_material_different_owners",
        resource::test_resource_token_material_different_owners,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_token_material_different_quotas",
        resource::test_resource_token_material_different_quotas,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_token_material_different_nonces",
        resource::test_resource_token_material_different_nonces,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_compute_signature_produces_64_bytes",
        resource::test_resource_compute_signature_produces_64_bytes,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_compute_signature_deterministic",
        resource::test_resource_compute_signature_deterministic,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_compute_signature_different_keys",
        resource::test_resource_compute_signature_different_keys,
        "capabilities/resource",
    ));
    suite.add(TestCase::new(
        "resource_compute_signature_different_material",
        resource::test_resource_compute_signature_different_material,
        "capabilities/resource",
    ));

    // Token tests (52 tests)
    suite.add(TestCase::new(
        "capability_token_empty",
        token::test_capability_token_empty,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_true",
        token::test_capability_token_grants_true,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_false",
        token::test_capability_token_grants_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_empty",
        token::test_capability_token_grants_empty,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_permission_count",
        token::test_capability_token_permission_count,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_has_any_permission_true",
        token::test_capability_token_has_any_permission_true,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_has_any_permission_false",
        token::test_capability_token_has_any_permission_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_all_true",
        token::test_capability_token_grants_all_true,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_all_false",
        token::test_capability_token_grants_all_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_all_empty",
        token::test_capability_token_grants_all_empty,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_any_true",
        token::test_capability_token_grants_any_true,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_any_false",
        token::test_capability_token_grants_any_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_grants_any_empty_caps",
        token::test_capability_token_grants_any_empty_caps,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_is_admin_true",
        token::test_capability_token_is_admin_true,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_is_admin_false",
        token::test_capability_token_is_admin_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_can_register_service_true",
        token::test_capability_token_can_register_service_true,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_can_register_service_false",
        token::test_capability_token_can_register_service_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "capability_token_display",
        token::test_capability_token_display,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "token_binary_size",
        token::test_token_binary_size,
        "capabilities/token",
    ));
    suite.add(TestCase::new("token_version", token::test_token_version, "capabilities/token"));
    suite.add(TestCase::new(
        "to_bytes_from_bytes_roundtrip",
        token::test_to_bytes_from_bytes_roundtrip,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "to_bytes_version_byte",
        token::test_to_bytes_version_byte,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "from_bytes_invalid_size",
        token::test_from_bytes_invalid_size,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "from_bytes_invalid_version",
        token::test_from_bytes_invalid_version,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "from_bytes_zero_expiry_becomes_none",
        token::test_from_bytes_zero_expiry_becomes_none,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "default_nonce_nonzero",
        token::test_default_nonce_nonzero,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "default_nonce_different_values",
        token::test_default_nonce_different_values,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "nonce_counter_increment",
        token::test_nonce_counter_increment,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "reset_nonce_counter",
        token::test_reset_nonce_counter,
        "capabilities/token",
    ));
    suite.add(TestCase::new("revoke_token", token::test_revoke_token, "capabilities/token"));
    suite.add(TestCase::new(
        "is_revoked_false",
        token::test_is_revoked_false,
        "capabilities/token",
    ));
    suite.add(TestCase::new("revoked_count", token::test_revoked_count, "capabilities/token"));
    suite.add(TestCase::new(
        "clear_revocations",
        token::test_clear_revocations,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "revoke_all_for_owner",
        token::test_revoke_all_for_owner,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "mac64_produces_64_bytes",
        token::test_mac64_produces_64_bytes,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "mac64_deterministic",
        token::test_mac64_deterministic,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "mac64_different_keys_different_output",
        token::test_mac64_different_keys_different_output,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "mac64_different_material_different_output",
        token::test_mac64_different_material_different_output,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "token_material_produces_32_bytes",
        token::test_token_material_produces_32_bytes,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "token_material_deterministic",
        token::test_token_material_deterministic,
        "capabilities/token",
    ));
    suite.add(TestCase::new(
        "token_material_different_inputs",
        token::test_token_material_different_inputs,
        "capabilities/token",
    ));

    // Types tests (19 tests)
    suite.add(TestCase::new(
        "capability_bit_values",
        types::test_capability_bit_values,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_bits_are_powers_of_two",
        types::test_capability_bits_are_powers_of_two,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_bits_are_unique",
        types::test_capability_bits_are_unique,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_all_returns_22_items",
        types::test_capability_all_returns_22_items,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_count_matches_all_len",
        types::test_capability_count_matches_all_len,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_core_exec",
        types::test_capability_as_str_core_exec,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_io",
        types::test_capability_as_str_io,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_network",
        types::test_capability_as_str_network,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_ipc",
        types::test_capability_as_str_ipc,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_memory",
        types::test_capability_as_str_memory,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_crypto",
        types::test_capability_as_str_crypto,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_filesystem",
        types::test_capability_as_str_filesystem,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_hardware",
        types::test_capability_as_str_hardware,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_debug",
        types::test_capability_as_str_debug,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_admin",
        types::test_capability_as_str_admin,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_as_str_register_service",
        types::test_capability_as_str_register_service,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_display_matches_as_str",
        types::test_capability_display_matches_as_str,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_clone",
        types::test_capability_clone,
        "capabilities/types",
    ));
    suite.add(TestCase::new("capability_copy", types::test_capability_copy, "capabilities/types"));
    suite.add(TestCase::new(
        "capability_equality",
        types::test_capability_equality,
        "capabilities/types",
    ));
    suite.add(TestCase::new(
        "capability_debug_format",
        types::test_capability_debug_format,
        "capabilities/types",
    ));

    let (_, failed, _) = suite.run_all();
    failed == 0
}
