[package]
name = "nonos_wallet"
version = "0.3.0"
edition = "2021"
publish = false
license = "AGPL-3.0"
authors = ["eK@nonos.systems"]
description = "NONOS native wallet capsule"

[[bin]]
name = "wallet_nonos"
path = "src/main.rs"

[dependencies]
nonos_libc = { package = "nonos_userland_libc", path = "../libc" }
nonos_app_skeleton = { path = "../app_skeleton" }
nonos_qr = { path = "../nonos_qr" }
nonos_hd = { path = "../nonos_hd" }
nonos_tls = { path = "../nonos_tls" }

[profile.release]
panic = "abort"
opt-level = 2
lto = false
debug = false
strip = true

[profile.dev]
panic = "abort"
opt-level = 0
debug = true
