-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_policy]: function definitions
import Aeneas
import Policy.Types
import Policy.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace nonos_policy

/-- [nonos_policy::arch::paging::descriptor::flags::PRESENT]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 27:0-27:32
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.PRESENT : Result Std.U64 := 1#u64 <<< 0#i32

/-- [nonos_policy::arch::paging::descriptor::flags::WRITABLE]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 30:0-30:33
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.WRITABLE : Result Std.U64 := 1#u64 <<< 1#i32

/-- [nonos_policy::arch::paging::descriptor::flags::USER]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 32:0-32:29
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.USER : Result Std.U64 := 1#u64 <<< 2#i32

/-- [nonos_policy::arch::paging::descriptor::flags::WRITE_THROUGH]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 33:0-33:38
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.WRITE_THROUGH : Result Std.U64 :=
  1#u64 <<< 3#i32

/-- [nonos_policy::arch::paging::descriptor::flags::NO_CACHE]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 35:0-35:33
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.NO_CACHE : Result Std.U64 := 1#u64 <<< 4#i32

/-- [nonos_policy::arch::paging::descriptor::flags::GLOBAL]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 42:0-42:31
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.GLOBAL : Result Std.U64 := 1#u64 <<< 8#i32

/-- [nonos_policy::arch::paging::descriptor::flags::NO_EXECUTE]
    Source: 'src/arch/paging/descriptor/../../../../../../../src/arch/paging/descriptor/flags.rs', lines 44:0-44:36
    Visibility: public -/
@[global_simps, irreducible]
def arch.paging.descriptor.flags.NO_EXECUTE : Result Std.U64 :=
  1#u64 <<< 63#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::contains]:
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 48:4-50:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.contains
  (self : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  let i ← lift (self.bits &&& other.bits)
  ok (i = other.bits)

/-- [nonos_policy::memory::paging::constants::permissions::PERM_WRITE_THROUGH]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/permissions.rs', lines 23:0-23:43
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_WRITE_THROUGH : Result Std.U32 :=
  1#u32 <<< 6#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::WRITE_THROUGH]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 31:4-31:70
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.WRITE_THROUGH
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_WRITE_THROUGH
  ok { bits := i }

/-- [nonos_policy::memory::paging::constants::permissions::PERM_NO_CACHE]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/permissions.rs', lines 22:0-22:38
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_NO_CACHE : Result Std.U32 :=
  1#u32 <<< 5#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::NO_CACHE]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 30:4-30:60
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.NO_CACHE
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_NO_CACHE
  ok { bits := i }

/-- [nonos_policy::memory::paging::constants::permissions::PERM_GLOBAL]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/permissions.rs', lines 21:0-21:36
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_GLOBAL : Result Std.U32 :=
  1#u32 <<< 4#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::GLOBAL]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 29:4-29:56
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.GLOBAL
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_GLOBAL
  ok { bits := i }

/-- [nonos_policy::memory::paging::constants::permissions::PERM_USER]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/permissions.rs', lines 20:0-20:34
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_USER : Result Std.U32 :=
  1#u32 <<< 3#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::USER]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 28:4-28:52
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.USER
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_USER
  ok { bits := i }

/-- [nonos_policy::memory::paging::constants::permissions::PERM_EXECUTE]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/permissions.rs', lines 19:0-19:37
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_EXECUTE : Result Std.U32 :=
  1#u32 <<< 2#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::EXECUTE]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 27:4-27:58
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.EXECUTE
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_EXECUTE
  ok { bits := i }

/-- [nonos_policy::memory::paging::constants::permissions::PERM_WRITE]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/permissions.rs', lines 18:0-18:35
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_WRITE : Result Std.U32 :=
  1#u32 <<< 1#i32

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::WRITE]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 26:4-26:54
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.WRITE
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_WRITE
  ok { bits := i }

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_NO_EXECUTE]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 35:0-35:50
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_NO_EXECUTE : Result Std.U64 :=
  arch.paging.descriptor.flags.NO_EXECUTE

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_GLOBAL]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 34:0-34:42
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_GLOBAL : Result Std.U64 :=
  arch.paging.descriptor.flags.GLOBAL

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_CACHE_DISABLE]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 30:0-30:51
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_CACHE_DISABLE : Result Std.U64 :=
  arch.paging.descriptor.flags.NO_CACHE

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_WRITE_THROUGH]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 29:0-29:56
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_WRITE_THROUGH : Result Std.U64 :=
  arch.paging.descriptor.flags.WRITE_THROUGH

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_USER]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 28:0-28:38
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_USER : Result Std.U64 :=
  arch.paging.descriptor.flags.USER

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_WRITABLE]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 27:0-27:46
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_WRITABLE : Result Std.U64 :=
  arch.paging.descriptor.flags.WRITABLE

/-- [nonos_policy::memory::paging::constants::pte_flags::PTE_PRESENT]
    Source: 'src/memory/paging/../../../../../../src/memory/paging/constants/pte_flags.rs', lines 26:0-26:44
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.pte_flags.PTE_PRESENT : Result Std.U64 :=
  arch.paging.descriptor.flags.PRESENT

/-- [nonos_policy::memory::paging::types::permissions::convert::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::to_pte_flags]:
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/convert.rs', lines 21:4-42:5
    Visibility: public -/
def memory.paging.types.permissions.convert.PagePermissions.to_pte_flags
  (self : memory.paging.types.permissions.flags.PagePermissions) :
  Result Std.U64
  := do
  let flags ← memory.paging.constants.pte_flags.PTE_PRESENT
  let pp ← memory.paging.types.permissions.flags.PagePermissions.WRITE
  let b ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp
  let flags1 ←
    if b
    then
      do
      let i ← memory.paging.constants.pte_flags.PTE_WRITABLE
      ok (flags ||| i)
    else ok flags
  let pp1 ← memory.paging.types.permissions.flags.PagePermissions.USER
  let b1 ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp1
  let flags2 ←
    if b1
    then
      do
      let i ← memory.paging.constants.pte_flags.PTE_USER
      ok (flags1 ||| i)
    else ok flags1
  let pp2 ←
    memory.paging.types.permissions.flags.PagePermissions.WRITE_THROUGH
  let b2 ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp2
  let flags3 ←
    if b2
    then
      do
      let i ← memory.paging.constants.pte_flags.PTE_WRITE_THROUGH
      ok (flags2 ||| i)
    else ok flags2
  let pp3 ← memory.paging.types.permissions.flags.PagePermissions.NO_CACHE
  let b3 ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp3
  let flags4 ←
    if b3
    then
      do
      let i ← memory.paging.constants.pte_flags.PTE_CACHE_DISABLE
      ok (flags3 ||| i)
    else ok flags3
  let pp4 ← memory.paging.types.permissions.flags.PagePermissions.GLOBAL
  let b4 ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp4
  let flags5 ←
    if b4
    then
      do
      let i ← memory.paging.constants.pte_flags.PTE_GLOBAL
      ok (flags4 ||| i)
    else ok flags4
  let pp5 ← memory.paging.types.permissions.flags.PagePermissions.EXECUTE
  let b5 ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp5
  if b5
  then ok flags5
  else
    let i ← memory.paging.constants.pte_flags.PTE_NO_EXECUTE
    ok (flags5 ||| i)

/-- [nonos_policy::to_pte_flags]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def to_pte_flags
  (p : memory.paging.types.permissions.flags.PagePermissions) :
  Result Std.U64
  := do
  memory.paging.types.permissions.convert.PagePermissions.to_pte_flags p

/-- [nonos_policy::memory::paging::types::permissions::flags::{nonos_policy::memory::paging::types::permissions::flags::PagePermissions}::is_wx_violation]:
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 60:4-62:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.is_wx_violation
  (self : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  let pp ← memory.paging.types.permissions.flags.PagePermissions.WRITE
  let b ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp
  if b
  then
    let pp1 ← memory.paging.types.permissions.flags.PagePermissions.EXECUTE
    memory.paging.types.permissions.flags.PagePermissions.contains self pp1
  else ok false

/-- [nonos_policy::is_wx_violation]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def is_wx_violation
  (p : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  memory.paging.types.permissions.flags.PagePermissions.is_wx_violation p

/-- [nonos_policy::usercopy::policy::USER_SPACE_END]
    Source: 'src/usercopy/../../../../../src/usercopy/policy.rs', lines 25:0-25:61 -/
@[global_simps, irreducible]
def usercopy.policy.USER_SPACE_END : Std.U64 := 140737488355327#u64

/-- [nonos_policy::usercopy::policy::MAX_COPY_SIZE]
    Source: 'src/usercopy/../../../../../src/usercopy/policy.rs', lines 27:0-27:57 -/
@[global_simps, irreducible]
def usercopy.policy.MAX_COPY_SIZE : Result Std.Usize := do
  let i ← 64#usize * 1024#usize
  i * 1024#usize

/-- [nonos_policy::usercopy::policy::check_range]:
    Source: 'src/usercopy/../../../../../src/usercopy/policy.rs', lines 35:0-50:1 -/
def usercopy.policy.check_range
  (addr : Std.U64) (len : Std.Usize) :
  Result (core.result.Result (Option usercopy.policy.UserRange)
    usercopy.error.UsercopyError)
  := do
  if addr = 0#u64
  then ok (core.result.Result.Err usercopy.error.UsercopyError.NullPointer)
  else
    let i ← usercopy.policy.MAX_COPY_SIZE
    if len > i
    then ok (core.result.Result.Err usercopy.error.UsercopyError.SizeTooLarge)
    else
      if len = 0#usize
      then ok (core.result.Result.Ok none)
      else
        let i1 ← lift (UScalar.cast .U64 len)
        let i2 ← i1 - 1#u64
        let o ← lift (U64.checked_add addr i2)
        let r ←
          core.option.Option.ok_or o
            usercopy.error.UsercopyError.AddressOverflow
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          if val > usercopy.policy.USER_SPACE_END
          then
            ok (core.result.Result.Err
              usercopy.error.UsercopyError.InvalidAddress)
          else
            let i3 ← lift (~~~ 4095#u64)
            let i4 ← lift (addr &&& i3)
            let i5 ← lift (~~~ 4095#u64)
            let i6 ← lift (val &&& i5)
            ok (core.result.Result.Ok (some
              { start_page := i4, end_page := i6 }))
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            (Option usercopy.policy.UserRange) (core.convert.FromSame
            usercopy.error.UsercopyError) residual

end nonos_policy
