-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_policy]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_policy

/-- [nonos_policy::memory::paging::types::permissions::flags::PagePermissions]
    Source: 'src/memory/paging/types/../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 20:0-22:1
    Visibility: public -/
structure memory.paging.types.permissions.flags.PagePermissions where
  bits : Std.U32

/-- [nonos_policy::usercopy::error::UsercopyError]
    Source: 'src/usercopy/../../../../../src/usercopy/error.rs', lines 20:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive usercopy.error.UsercopyError where
| NullPointer : usercopy.error.UsercopyError
| InvalidAddress : usercopy.error.UsercopyError
| AddressOverflow : usercopy.error.UsercopyError
| MisalignedAddress : usercopy.error.UsercopyError
| PageNotMapped : usercopy.error.UsercopyError
| PageNotUser : usercopy.error.UsercopyError
| PageNotWritable : usercopy.error.UsercopyError
| PageTableCorrupt : usercopy.error.UsercopyError
| PageFault : usercopy.error.UsercopyError
| NoProcessContext : usercopy.error.UsercopyError
| SizeTooLarge : usercopy.error.UsercopyError
| InvalidUtf8 : usercopy.error.UsercopyError

/-- [nonos_policy::usercopy::policy::UserRange]
    Source: 'src/usercopy/../../../../../src/usercopy/policy.rs', lines 30:0-33:1 -/
structure usercopy.policy.UserRange where
  start_page : Std.U64
  end_page : Std.U64

end nonos_policy
