// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! A Poseidon hash over the Goldilocks field, and the AIR that proves knowledge
//! of a preimage. The permutation has real parameters, not a demonstration:
//!
//!  - width 8, a rate of 4 and a capacity of 4 (a 256-bit capacity, so the
//!    sponge targets 128-bit security),
//!  - the x^7 S-box, which is a permutation of this field because 7 is coprime
//!    to the group order,
//!  - a maximum-distance-separable diffusion matrix built as a Cauchy matrix,
//!    which is provably MDS for any distinct node sets,
//!  - a full S-box layer every round (no partial rounds), so the round function
//!    is uniform and every lane is fully mixed each round,
//!  - round constants generated by a nothing-up-my-sleeve rule, the BLAKE3 hash
//!    of a domain string with the round and lane indices, so they are
//!    reproducible and free of hidden structure.
//!
//! The capacity lane group is initialized to zero at the first row, the sponge
//! domain separation. The proof shows a public digest, the rate lanes at the
//! final row, is the hash of some input the proof never reveals: knowledge of a
//! preimage.

use super::super::field::Fp;
use super::spec::Air;
use crate::crypto::hash::blake3_hash;
use alloc::vec::Vec;

/// State width in field elements.
pub const WIDTH: usize = 8;
/// Rate: the number of lanes that absorb input and emit the digest.
pub const RATE: usize = 4;

const RC_DOMAIN: &[u8] = b"NONOS-POSEIDON-GOLDILOCKS-RC";

pub struct Poseidon {
    log_t: u32,
    mds: [[Fp; WIDTH]; WIDTH],
    rc: Vec<[Fp; WIDTH]>,
    digest: [Fp; RATE],
}

impl Poseidon {
    /// Build the hash and its preimage AIR for `2^log_t` rounds and a public
    /// `digest`.
    pub fn new(log_t: u32, digest: [Fp; RATE]) -> Poseidon {
        let rounds = 1usize << log_t;
        Poseidon { log_t, mds: cauchy_mds(), rc: round_constants(rounds), digest }
    }

    /// One round of the permutation on a full state: full x^7 S-box layer, then
    /// the MDS mix, then the round constants. Used by the prover to build the
    /// trace and by callers to compute a digest.
    pub fn round(&self, state: &[Fp; WIDTH], round: usize) -> [Fp; WIDTH] {
        let mut sbox = [Fp::ZERO; WIDTH];
        for (s, v) in sbox.iter_mut().zip(state.iter()) {
            *s = (*v).pow(7);
        }
        let mut out = [Fp::ZERO; WIDTH];
        for (j, o) in out.iter_mut().enumerate() {
            let mut acc = self.rc[round][j];
            for (m, s) in self.mds[j].iter().zip(sbox.iter()) {
                acc = acc + *m * *s;
            }
            *o = acc;
        }
        out
    }

    /// Hash a rate-sized input: seed the capacity with zero, run every round but
    /// the last, and read the digest from the final rate lanes.
    pub fn hash(&self, input: &[Fp; RATE]) -> [Fp; RATE] {
        let mut state = [Fp::ZERO; WIDTH];
        state[..RATE].copy_from_slice(input);
        let rounds = 1usize << self.log_t;
        for r in 0..rounds - 1 {
            state = self.round(&state, r);
        }
        let mut digest = [Fp::ZERO; RATE];
        digest.copy_from_slice(&state[..RATE]);
        digest
    }
}

impl Air for Poseidon {
    fn log_trace_len(&self) -> u32 {
        self.log_t
    }

    fn trace_width(&self) -> usize {
        WIDTH
    }

    fn window_size(&self) -> usize {
        2
    }

    fn constraint_degree(&self) -> usize {
        7
    }

    fn num_transition(&self) -> usize {
        WIDTH
    }

    fn periodic_columns(&self) -> Vec<Vec<Fp>> {
        // One column per lane: the round constant for that lane at each round.
        (0..WIDTH).map(|j| self.rc.iter().map(|row| row[j]).collect()).collect()
    }

    fn transition(&self, window: &[Fp], periodic: &[Fp]) -> Vec<Fp> {
        // window = [state (WIDTH), next state (WIDTH)]; periodic = rc lanes at x.
        let mut sbox = [Fp::ZERO; WIDTH];
        for (s, v) in sbox.iter_mut().zip(window[..WIDTH].iter()) {
            *s = (*v).pow(7);
        }
        let mut out = Vec::with_capacity(WIDTH);
        for j in 0..WIDTH {
            let mut acc = periodic[j];
            for (m, s) in self.mds[j].iter().zip(sbox.iter()) {
                acc = acc + *m * *s;
            }
            out.push(window[WIDTH + j] - acc);
        }
        out
    }

    fn boundary(&self) -> Vec<(usize, usize, Fp)> {
        let last = (1usize << self.log_t) - 1;
        let mut b = Vec::with_capacity(WIDTH);
        // Capacity lanes initialized to zero: the sponge domain separation.
        for j in RATE..WIDTH {
            b.push((j, 0, Fp::ZERO));
        }
        // Final rate lanes are the public digest.
        for (j, d) in self.digest.iter().enumerate() {
            b.push((j, last, *d));
        }
        b
    }
}

/// A Cauchy matrix `M[i][j] = 1 / (x_i - y_j)` with disjoint node sets
/// `x_i = i` and `y_j = WIDTH + j`. Cauchy matrices are MDS for any distinct
/// nodes, so this is a real diffusion layer.
fn cauchy_mds() -> [[Fp; WIDTH]; WIDTH] {
    let mut m = [[Fp::ZERO; WIDTH]; WIDTH];
    for (i, row) in m.iter_mut().enumerate() {
        for (j, cell) in row.iter_mut().enumerate() {
            let x = Fp::from_u64(i as u64);
            let y = Fp::from_u64((WIDTH + j) as u64);
            *cell = (x - y).inv();
        }
    }
    m
}

/// Nothing-up-my-sleeve round constants: the BLAKE3 hash of a domain string with
/// the round and lane indices, reduced into the field.
fn round_constants(rounds: usize) -> Vec<[Fp; WIDTH]> {
    let mut rc = Vec::with_capacity(rounds);
    for r in 0..rounds {
        let mut row = [Fp::ZERO; WIDTH];
        for (j, cell) in row.iter_mut().enumerate() {
            let mut buf = Vec::with_capacity(RC_DOMAIN.len() + 16);
            buf.extend_from_slice(RC_DOMAIN);
            buf.extend_from_slice(&(r as u64).to_le_bytes());
            buf.extend_from_slice(&(j as u64).to_le_bytes());
            let h = blake3_hash(&buf);
            let v = u64::from_le_bytes([h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]]);
            *cell = Fp::from_u64(v);
        }
        rc.push(row);
    }
    rc
}
