pub struct Context {
    pub base: u64,
    pub width: u32,
    pub height: u32,
    pub stride: u32,
    pub compositor_port: u32,
    pub router_port: u32,
    pub policy_port: u32,
    pub step: u8,
    pub kbd_sel: u8,
    pub wall_sel: u8,
    pub pass_len: usize,
    pub pass_buf: [u8; 64],
    pub keys_done: bool,
    pub keygen_stage: u8,
    pub lang_sel: u8,
    pub tz_off: i8,
    pub theme_sel: u8,
    pub net_sel: u8,
    pub persist_sel: u8,
    pub privacy: u16,
    pub admin_len: usize,
    pub admin_buf: [u8; 64],
    pub host_len: usize,
    pub host_buf: [u8; 64],
}

impl Context {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        base: u64,
        width: u32,
        height: u32,
        stride: u32,
        compositor_port: u32,
        router_port: u32,
        policy_port: u32,
    ) -> Self {
        Self {
            base,
            width,
            height,
            stride,
            compositor_port,
            router_port,
            policy_port,
            step: 0,
            kbd_sel: 0,
            wall_sel: 0,
            pass_len: 0,
            pass_buf: [0u8; 64],
            keys_done: false,
            keygen_stage: 0,
            lang_sel: 0,
            tz_off: 0,
            theme_sel: 0,
            net_sel: 0,
            persist_sel: 0,
            privacy: 0b0000_0011,
            admin_len: 0,
            admin_buf: [0u8; 64],
            host_len: 0,
            host_buf: [0u8; 64],
        }
    }
}
