# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# choose: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := choose
CAPSULE_HANDLE             := choose
CAPSULE_DIR                := userland/capsule_choose
CAPSULE_BIN_NAME           := choose
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.choose
CAPSULE_SERVICE_ENDPOINT   := service:4908:tool.choose
CAPSULE_REPLY_ENDPOINT     := reply:4909:endpoint.tool.choose.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-choose/bin/choose
CAPSULE_METADATA           := crates.io choose publisher

include nonos-mk/capsule.mk
