[package]
name = "nonos_capsule_boot_splash"
version = "0.3.0"
edition = "2021"
publish = false

[[bin]]
name = "boot_splash"
path = "src/main.rs"

[dependencies]
nonos_libc = { package = "nonos_userland_libc", path = "../libc" }
nonos_toolkit = { package = "nonos_toolkit", path = "../toolkit" }

[features]
default = []
