#!/usr/bin/env python3
# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""Emit the [bits] section of the capability ABI from the kernel table.

Written rather than maintained, because a hand kept copy of a table is a second
answer to a question that already has one, and the two only have to disagree
once for a toolchain to grant a permission nobody asked for.

Only [bits] is generated. Groups and delegation are policy: which capabilities
belong together is a decision, not a fact derivable from the enum, so this
prints them back unchanged and reports any name they use that no longer
resolves.
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from check_caps_abi import read_kernel, sections  # noqa: E402

ABI_CAPS = Path("abi/caps.toml")
HEADER = ("# Generated by scripts/gen_caps_abi.py from\n"
          "# src/capabilities/types/bit.rs. Do not edit [bits] by hand.\n")


def screaming(name: str) -> str:
    """CamelCase to the SCREAMING_SNAKE the rest of the ABI files use.

    A run of capitals is one word, so `IPC` stays `IPC` rather than becoming
    `I_P_C`, and `GraphicsDisplayQuery` still separates on each word.
    """
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])",
                  "_", name).upper()


def emit_bits(kernel) -> str:
    rows = sorted(((n, b) for n, b in kernel.values()), key=lambda kv: kv[1])
    width = max(len(screaming(n)) for n, _ in rows)
    out = ["[bits]"]
    for name, bit in rows:
        grouped = f"{bit:016X}"
        pretty = "_".join(grouped[i:i + 4] for i in range(0, 16, 4))
        out.append(f"{screaming(name):<{width}} = 0x{pretty}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path("."), help="repository root")
    ap.add_argument("--write", action="store_true",
                    help="replace [bits] in abi/caps.toml instead of printing it")
    args = ap.parse_args()

    try:
        kernel = read_kernel(args.root)
        text = (args.root / ABI_CAPS).read_text()
    except FileNotFoundError as e:
        print(f"gen-caps-abi: {e}", file=sys.stderr)
        return 2

    published = {screaming(n) for n, _ in kernel.values()}
    stale = set()
    for group in ("groups", "delegation"):
        for _, raw in sections(text).get(group, []):
            stale.update(n for n in re.findall(r'"([^"]+)"', raw)
                         if n not in published)

    bits = emit_bits(kernel)
    if not args.write:
        print(HEADER + bits, end="")
    else:
        head, _, rest = text.partition("[bits]")
        _, _, tail = rest.partition("\n[")
        (args.root / ABI_CAPS).write_text(head + HEADER + bits + "\n[" + tail)
        print(f"gen-caps-abi: wrote {len(kernel)} bits to {ABI_CAPS}")

    if stale:
        print(f"gen-caps-abi: {len(stale)} names used by groups no longer exist: "
              + ", ".join(sorted(stale)), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
