// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Maps a capsule's spawn name to its embedded attestation trailer, generated by
// the host signing pipeline as nonos-data/trust/capsules/<name>.zk_trailer.bin
// (the same directory as each capsule's cert and manifest). The spawn path looks
// the trailer up by name; a capsule with no entry has no trailer yet and is left
// to the rollout policy in preflight. New capsules are added one line at a time
// as their sidecars are reconciled.

macro_rules! trailer {
    ($file:literal) => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/nonos-data/trust/capsules/",
            $file,
            ".zk_trailer.bin"
        )) as &'static [u8]
    };
}

// Return the embedded attestation trailer for a capsule spawn name, or None when
// the capsule has no sidecar yet.
pub fn trailer_for(name: &str) -> Option<&'static [u8]> {
    let bytes: &'static [u8] = match name {
        "app.terminal" => trailer!("terminal"),
        _ => return None,
    };
    Some(bytes)
}
