# NONOS userland: capsule_driver_rtl8821ce
# eK@nonos.systems

[package]
name = "nonos_capsule_driver_rtl8821ce"
version = "0.3.0"
edition = "2021"
publish = false
license = "AGPL-3.0"
authors = ["eK@nonos.systems"]
description = "NONOS userland Realtek RTL8821CE wifi driver capsule"

[[bin]]
name = "driver_rtl8821ce"
path = "src/main.rs"

[dependencies]
nonos_libc = { package = "nonos_userland_libc", path = "../libc" }
nonos_mac = { path = "../nonos_mac" }
nonos_wifi_core = { path = "../nonos_wifi_core" }

[profile.release]
panic = "abort"
opt-level = 2
lto = false
debug = false
strip = true
