-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_caps]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_caps

/-- [nonos_caps::capabilities::types::Capability]
    Source: 'src/capabilities/../../../../../src/capabilities/types.rs', lines 18:0-51:1
    Visibility: public -/
@[discriminant isize]
inductive capabilities.types.Capability where
| CoreExec : capabilities.types.Capability
| IO : capabilities.types.Capability
| Network : capabilities.types.Capability
| IPC : capabilities.types.Capability
| Memory : capabilities.types.Capability
| Crypto : capabilities.types.Capability
| FileSystem : capabilities.types.Capability
| Hardware : capabilities.types.Capability
| Debug : capabilities.types.Capability
| Admin : capabilities.types.Capability
| RegisterService : capabilities.types.Capability
| GraphicsDisplayQuery : capabilities.types.Capability
| GraphicsSurfaceCreate : capabilities.types.Capability
| GraphicsSurfaceMap : capabilities.types.Capability
| GraphicsPresent : capabilities.types.Capability
| DeviceEnum : capabilities.types.Capability
| Driver : capabilities.types.Capability
| Mmio : capabilities.types.Capability
| Irq : capabilities.types.Capability
| Dma : capabilities.types.Capability
| Pio : capabilities.types.Capability
| InputSource : capabilities.types.Capability
| TimeSet : capabilities.types.Capability

/-- [nonos_caps::capabilities::types::{nonos_caps::capabilities::types::Capability}::bit]:
    Source: 'src/capabilities/../../../../../src/capabilities/types.rs', lines 55:4-81:5 -/
def capabilities.types.Capability.bit
  (self : capabilities.types.Capability) : Result Std.U64 := do
  match self with
  | capabilities.types.Capability.CoreExec => ok 1#u64
  | capabilities.types.Capability.IO => ok 2#u64
  | capabilities.types.Capability.Network => ok 4#u64
  | capabilities.types.Capability.IPC => ok 8#u64
  | capabilities.types.Capability.Memory => ok 16#u64
  | capabilities.types.Capability.Crypto => ok 32#u64
  | capabilities.types.Capability.FileSystem => ok 64#u64
  | capabilities.types.Capability.Hardware => ok 128#u64
  | capabilities.types.Capability.Debug => ok 256#u64
  | capabilities.types.Capability.Admin => ok 512#u64
  | capabilities.types.Capability.RegisterService => ok 1024#u64
  | capabilities.types.Capability.GraphicsDisplayQuery => ok 2048#u64
  | capabilities.types.Capability.GraphicsSurfaceCreate => ok 4096#u64
  | capabilities.types.Capability.GraphicsSurfaceMap => ok 8192#u64
  | capabilities.types.Capability.GraphicsPresent => ok 16384#u64
  | capabilities.types.Capability.DeviceEnum => ok 32768#u64
  | capabilities.types.Capability.Driver => ok 65536#u64
  | capabilities.types.Capability.Mmio => ok 131072#u64
  | capabilities.types.Capability.Irq => ok 262144#u64
  | capabilities.types.Capability.Dma => ok 524288#u64
  | capabilities.types.Capability.Pio => ok 1048576#u64
  | capabilities.types.Capability.InputSource => ok 2097152#u64
  | capabilities.types.Capability.TimeSet => ok 4194304#u64

/-- [nonos_caps::capabilities::bits::has_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 34:0-36:1
    Visibility: public -/
def capabilities.bits.has_capability
  (bits : Std.U64) (cap : capabilities.types.Capability) : Result Bool := do
  let i ← capabilities.types.Capability.bit cap
  let i1 ← lift (bits &&& i)
  ok (i1 != 0#u64)

/-- [nonos_caps::capabilities::bits::add_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 39:0-41:1
    Visibility: public -/
def capabilities.bits.add_capability
  (bits : Std.U64) (cap : capabilities.types.Capability) : Result Std.U64 := do
  let i ← capabilities.types.Capability.bit cap
  ok (bits ||| i)

/-- [nonos_caps::capabilities::bits::remove_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 44:0-46:1
    Visibility: public -/
def capabilities.bits.remove_capability
  (bits : Std.U64) (cap : capabilities.types.Capability) : Result Std.U64 := do
  let i ← capabilities.types.Capability.bit cap
  let i1 ← lift (~~~ i)
  ok (bits &&& i1)

end nonos_caps
