-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_caps]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_caps

/-- [nonos_caps::capabilities::types::defs::Capability]
    Source: 'src/capabilities/../../../../../src/capabilities/types/defs.rs', lines 18:0-86:1
    Visibility: public -/
@[discriminant isize]
inductive capabilities.types.defs.Capability where
| CoreExec : capabilities.types.defs.Capability
| IO : capabilities.types.defs.Capability
| Network : capabilities.types.defs.Capability
| IPC : capabilities.types.defs.Capability
| Memory : capabilities.types.defs.Capability
| Crypto : capabilities.types.defs.Capability
| FileSystem : capabilities.types.defs.Capability
| Hardware : capabilities.types.defs.Capability
| Debug : capabilities.types.defs.Capability
| Admin : capabilities.types.defs.Capability
| RegisterService : capabilities.types.defs.Capability
| GraphicsDisplayQuery : capabilities.types.defs.Capability
| GraphicsSurfaceCreate : capabilities.types.defs.Capability
| GraphicsSurfaceMap : capabilities.types.defs.Capability
| GraphicsPresent : capabilities.types.defs.Capability
| DeviceEnum : capabilities.types.defs.Capability
| Driver : capabilities.types.defs.Capability
| Mmio : capabilities.types.defs.Capability
| Irq : capabilities.types.defs.Capability
| Dma : capabilities.types.defs.Capability
| Pio : capabilities.types.defs.Capability
| InputSource : capabilities.types.defs.Capability
| TimeSet : capabilities.types.defs.Capability
| SpawnBroker : capabilities.types.defs.Capability
| SpawnWindow : capabilities.types.defs.Capability
| ProcessControl : capabilities.types.defs.Capability
| StoreWrite : capabilities.types.defs.Capability
| EnrolDevRoot : capabilities.types.defs.Capability
| Keyring : capabilities.types.defs.Capability
| Entropy : capabilities.types.defs.Capability
| AppInstall : capabilities.types.defs.Capability

/-- [nonos_caps::capabilities::types::bit::{nonos_caps::capabilities::types::defs::Capability}::bit]:
    Source: 'src/capabilities/../../../../../src/capabilities/types/bit.rs', lines 21:4-55:5 -/
def capabilities.types.bit.Capability.bit
  (self : capabilities.types.defs.Capability) : Result Std.U64 := do
  match self with
  | capabilities.types.defs.Capability.CoreExec => ok 1#u64
  | capabilities.types.defs.Capability.IO => ok 2#u64
  | capabilities.types.defs.Capability.Network => ok 4#u64
  | capabilities.types.defs.Capability.IPC => ok 8#u64
  | capabilities.types.defs.Capability.Memory => ok 16#u64
  | capabilities.types.defs.Capability.Crypto => ok 32#u64
  | capabilities.types.defs.Capability.FileSystem => ok 64#u64
  | capabilities.types.defs.Capability.Hardware => ok 128#u64
  | capabilities.types.defs.Capability.Debug => ok 256#u64
  | capabilities.types.defs.Capability.Admin => ok 512#u64
  | capabilities.types.defs.Capability.RegisterService => ok 1024#u64
  | capabilities.types.defs.Capability.GraphicsDisplayQuery => ok 2048#u64
  | capabilities.types.defs.Capability.GraphicsSurfaceCreate => ok 4096#u64
  | capabilities.types.defs.Capability.GraphicsSurfaceMap => ok 8192#u64
  | capabilities.types.defs.Capability.GraphicsPresent => ok 16384#u64
  | capabilities.types.defs.Capability.DeviceEnum => ok 32768#u64
  | capabilities.types.defs.Capability.Driver => ok 65536#u64
  | capabilities.types.defs.Capability.Mmio => ok 131072#u64
  | capabilities.types.defs.Capability.Irq => ok 262144#u64
  | capabilities.types.defs.Capability.Dma => ok 524288#u64
  | capabilities.types.defs.Capability.Pio => ok 1048576#u64
  | capabilities.types.defs.Capability.InputSource => ok 2097152#u64
  | capabilities.types.defs.Capability.TimeSet => ok 4194304#u64
  | capabilities.types.defs.Capability.SpawnBroker => ok 8388608#u64
  | capabilities.types.defs.Capability.SpawnWindow => ok 16777216#u64
  | capabilities.types.defs.Capability.ProcessControl => ok 33554432#u64
  | capabilities.types.defs.Capability.StoreWrite => ok 67108864#u64
  | capabilities.types.defs.Capability.EnrolDevRoot => ok 134217728#u64
  | capabilities.types.defs.Capability.Keyring => ok 268435456#u64
  | capabilities.types.defs.Capability.Entropy => ok 536870912#u64
  | capabilities.types.defs.Capability.AppInstall => ok 1073741824#u64

/-- [nonos_caps::capabilities::bits::has_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 34:0-36:1
    Visibility: public -/
def capabilities.bits.has_capability
  (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
  Result Bool
  := do
  let i ← capabilities.types.bit.Capability.bit cap
  let i1 ← lift (bits &&& i)
  ok (i1 != 0#u64)

/-- [nonos_caps::capabilities::bits::add_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 39:0-41:1
    Visibility: public -/
def capabilities.bits.add_capability
  (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
  Result Std.U64
  := do
  let i ← capabilities.types.bit.Capability.bit cap
  ok (bits ||| i)

/-- [nonos_caps::capabilities::bits::remove_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 44:0-46:1
    Visibility: public -/
def capabilities.bits.remove_capability
  (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
  Result Std.U64
  := do
  let i ← capabilities.types.bit.Capability.bit cap
  let i1 ← lift (~~~ i)
  ok (bits &&& i1)

end nonos_caps
