-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_caps]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_caps

/-- [nonos_caps::capabilities::types::defs::Capability]
    Source: 'src/capabilities/../../../../../src/capabilities/types/table.rs', lines 22:8-24:9
    Visibility: public -/
@[discriminant isize]
inductive capabilities.types.defs.Capability where
| CoreExec : capabilities.types.defs.Capability
| IO : capabilities.types.defs.Capability
| Network : capabilities.types.defs.Capability
| IPC : capabilities.types.defs.Capability
| Memory : capabilities.types.defs.Capability
| Crypto : capabilities.types.defs.Capability
| FileSystem : capabilities.types.defs.Capability
| Hardware : capabilities.types.defs.Capability
| Debug : capabilities.types.defs.Capability
| Admin : capabilities.types.defs.Capability
| RegisterService : capabilities.types.defs.Capability
| GraphicsDisplayQuery : capabilities.types.defs.Capability
| GraphicsSurfaceCreate : capabilities.types.defs.Capability
| GraphicsSurfaceMap : capabilities.types.defs.Capability
| GraphicsPresent : capabilities.types.defs.Capability
| DeviceEnum : capabilities.types.defs.Capability
| Driver : capabilities.types.defs.Capability
| Mmio : capabilities.types.defs.Capability
| Irq : capabilities.types.defs.Capability
| Dma : capabilities.types.defs.Capability
| Pio : capabilities.types.defs.Capability
| InputSource : capabilities.types.defs.Capability
| TimeSet : capabilities.types.defs.Capability
| SpawnBroker : capabilities.types.defs.Capability
| SpawnWindow : capabilities.types.defs.Capability
| ProcessControl : capabilities.types.defs.Capability
| StoreWrite : capabilities.types.defs.Capability
| EnrolDevRoot : capabilities.types.defs.Capability
| Keyring : capabilities.types.defs.Capability
| Entropy : capabilities.types.defs.Capability
| AppInstall : capabilities.types.defs.Capability
| AttestRead : capabilities.types.defs.Capability
| ForeignExec : capabilities.types.defs.Capability
| LocalSign : capabilities.types.defs.Capability

/-- [nonos_caps::capabilities::types::defs::{nonos_caps::capabilities::types::defs::Capability}::bit]:
    Source: 'src/capabilities/../../../../../src/capabilities/types/table.rs', lines 28:12-32:13 -/
def capabilities.types.defs.Capability.bit
  (self : capabilities.types.defs.Capability) : Result Std.U64 := do
  match self with
  | capabilities.types.defs.Capability.CoreExec => 1#u64 <<< 0#i32
  | capabilities.types.defs.Capability.IO => 1#u64 <<< 1#i32
  | capabilities.types.defs.Capability.Network => 1#u64 <<< 2#i32
  | capabilities.types.defs.Capability.IPC => 1#u64 <<< 3#i32
  | capabilities.types.defs.Capability.Memory => 1#u64 <<< 4#i32
  | capabilities.types.defs.Capability.Crypto => 1#u64 <<< 5#i32
  | capabilities.types.defs.Capability.FileSystem => 1#u64 <<< 6#i32
  | capabilities.types.defs.Capability.Hardware => 1#u64 <<< 7#i32
  | capabilities.types.defs.Capability.Debug => 1#u64 <<< 8#i32
  | capabilities.types.defs.Capability.Admin => 1#u64 <<< 9#i32
  | capabilities.types.defs.Capability.RegisterService => 1#u64 <<< 10#i32
  | capabilities.types.defs.Capability.GraphicsDisplayQuery => 1#u64 <<< 11#i32
  | capabilities.types.defs.Capability.GraphicsSurfaceCreate =>
    1#u64 <<< 12#i32
  | capabilities.types.defs.Capability.GraphicsSurfaceMap => 1#u64 <<< 13#i32
  | capabilities.types.defs.Capability.GraphicsPresent => 1#u64 <<< 14#i32
  | capabilities.types.defs.Capability.DeviceEnum => 1#u64 <<< 15#i32
  | capabilities.types.defs.Capability.Driver => 1#u64 <<< 16#i32
  | capabilities.types.defs.Capability.Mmio => 1#u64 <<< 17#i32
  | capabilities.types.defs.Capability.Irq => 1#u64 <<< 18#i32
  | capabilities.types.defs.Capability.Dma => 1#u64 <<< 19#i32
  | capabilities.types.defs.Capability.Pio => 1#u64 <<< 20#i32
  | capabilities.types.defs.Capability.InputSource => 1#u64 <<< 21#i32
  | capabilities.types.defs.Capability.TimeSet => 1#u64 <<< 22#i32
  | capabilities.types.defs.Capability.SpawnBroker => 1#u64 <<< 23#i32
  | capabilities.types.defs.Capability.SpawnWindow => 1#u64 <<< 24#i32
  | capabilities.types.defs.Capability.ProcessControl => 1#u64 <<< 25#i32
  | capabilities.types.defs.Capability.StoreWrite => 1#u64 <<< 26#i32
  | capabilities.types.defs.Capability.EnrolDevRoot => 1#u64 <<< 27#i32
  | capabilities.types.defs.Capability.Keyring => 1#u64 <<< 28#i32
  | capabilities.types.defs.Capability.Entropy => 1#u64 <<< 29#i32
  | capabilities.types.defs.Capability.AppInstall => 1#u64 <<< 30#i32
  | capabilities.types.defs.Capability.AttestRead => 1#u64 <<< 31#i32
  | capabilities.types.defs.Capability.ForeignExec => 1#u64 <<< 32#i32
  | capabilities.types.defs.Capability.LocalSign => 1#u64 <<< 33#i32

/-- [nonos_caps::capabilities::bits::has_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 34:0-36:1
    Visibility: public -/
def capabilities.bits.has_capability
  (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
  Result Bool
  := do
  let i ← capabilities.types.defs.Capability.bit cap
  let i1 ← lift (bits &&& i)
  ok (i1 != 0#u64)

/-- [nonos_caps::capabilities::bits::add_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 39:0-41:1
    Visibility: public -/
def capabilities.bits.add_capability
  (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
  Result Std.U64
  := do
  let i ← capabilities.types.defs.Capability.bit cap
  ok (bits ||| i)

/-- [nonos_caps::capabilities::bits::remove_capability]:
    Source: 'src/capabilities/../../../../../src/capabilities/bits.rs', lines 44:0-46:1
    Visibility: public -/
def capabilities.bits.remove_capability
  (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
  Result Std.U64
  := do
  let i ← capabilities.types.defs.Capability.bit cap
  let i1 ← lift (~~~ i)
  ok (bits &&& i1)

end nonos_caps
