-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_irq]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace nonos_irq

/-- [core::option::{core::option::Option<T>}::ok_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1334:4-1334:73
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or"]
axiom core.option.Option.ok_or
  {T : Type} {E : Type} : Option T → E → Result (core.result.Result T E)

/-- [nonos_irq::irq::types::BIND_MSIX]
    Source: 'src/irq/../../../../../src/hardware/broker/irq/types.rs', lines 26:0-26:34
    Visibility: public -/
@[global_simps, irreducible]
def irq.types.BIND_MSIX : Result Std.U32 := 1#u32 <<< 0#i32

/-- [nonos_irq::irq::types::FLAGS_KNOWN]
    Source: 'src/irq/../../../../../src/hardware/broker/irq/types.rs', lines 27:0-27:39
    Visibility: public -/
@[global_simps, irreducible]
def irq.types.FLAGS_KNOWN : Result Std.U32 := irq.types.BIND_MSIX

/-- [nonos_irq::irq::types::IrqBindRequest]
    Source: 'src/irq/../../../../../src/hardware/broker/irq/types.rs', lines 53:0-65:1
    Visibility: public -/
structure irq.types.IrqBindRequest where
  device_id : Std.U64
  claim_epoch : Std.U64
  irq_source : Std.U32
  flags : Std.U32
  vector_count : Std.U32

/-- [nonos_irq::irq::types::IrqBindError]
    Source: 'src/irq/../../../../../src/hardware/broker/irq/types.rs', lines 78:0-95:1
    Visibility: public -/
@[discriminant isize]
inductive irq.types.IrqBindError where
| NotClaimed : irq.types.IrqBindError
| StaleEpoch : irq.types.IrqBindError
| UnknownDevice : irq.types.IrqBindError
| NotDeviceIrq : irq.types.IrqBindError
| AlreadyBound : irq.types.IrqBindError
| ReservedGsi : irq.types.IrqBindError
| NoVector : irq.types.IrqBindError
| UnsupportedFlags : irq.types.IrqBindError
| NotIntx : irq.types.IrqBindError
| NoMsixCap : irq.types.IrqBindError
| BadMsixBar : irq.types.IrqBindError
| BadVectorCount : irq.types.IrqBindError
| MsixProgramFailed : irq.types.IrqBindError
| NoDeviceHandle : irq.types.IrqBindError
| PlatformError : irq.types.IrqBindError

/-- [nonos_irq::irq::validate::MsixHandleView]
    Source: 'src/irq/../../../../../src/hardware/broker/irq/validate.rs', lines 46:0-53:1 -/
structure irq.validate.MsixHandleView where
  msix_present : Bool
  msix_table_size : Std.U16
  table_bar_in_range : Bool
  table_bar_is_mmio : Bool
  pba_bar_in_range : Bool
  pba_bar_is_mmio : Bool

/-- [nonos_irq::irq::validate::validate_msix_request]:
    Source: 'src/irq/../../../../../src/hardware/broker/irq/validate.rs', lines 74:0-117:1 -/
def irq.validate.validate_msix_request
  (req : irq.types.IrqBindRequest) (pool_capacity : Std.Usize)
  (handle : Option irq.validate.MsixHandleView)
  (has_existing_msix_grant : Bool) :
  Result (core.result.Result Unit irq.types.IrqBindError)
  := do
  let i ← irq.types.FLAGS_KNOWN
  let i1 ← lift (~~~ i)
  let i2 ← lift (req.flags &&& i1)
  if i2 != 0#u32
  then ok (core.result.Result.Err irq.types.IrqBindError.UnsupportedFlags)
  else
    let i3 ← irq.types.BIND_MSIX
    let i4 ← lift (req.flags &&& i3)
    if i4 = 0#u32
    then ok (core.result.Result.Err irq.types.IrqBindError.UnsupportedFlags)
    else
      let n ← lift (UScalar.cast .Usize req.vector_count)
      if n = 0#usize
      then ok (core.result.Result.Err irq.types.IrqBindError.BadVectorCount)
      else
        if n > pool_capacity
        then ok (core.result.Result.Err irq.types.IrqBindError.BadVectorCount)
        else
          let r ←
            core.option.Option.ok_or handle
              irq.types.IrqBindError.NoDeviceHandle
          let cf ← core.result.Result.Insts.CoreOpsTry.branch r
          match cf with
          | core.ops.control_flow.ControlFlow.Continue val =>
            if val.msix_present
            then
              let i5 ← lift (UScalar.cast .U16 n)
              if i5 > val.msix_table_size
              then
                ok (core.result.Result.Err
                  irq.types.IrqBindError.BadVectorCount)
              else
                if val.table_bar_in_range
                then
                  if val.table_bar_is_mmio
                  then
                    if val.pba_bar_in_range
                    then
                      if val.pba_bar_is_mmio
                      then
                        if req.irq_source != 0#u32
                        then
                          ok (core.result.Result.Err
                            irq.types.IrqBindError.NotDeviceIrq)
                        else
                          if has_existing_msix_grant
                          then
                            ok (core.result.Result.Err
                              irq.types.IrqBindError.AlreadyBound)
                          else ok (core.result.Result.Ok ())
                      else
                        ok (core.result.Result.Err
                          irq.types.IrqBindError.BadMsixBar)
                    else
                      ok (core.result.Result.Err
                        irq.types.IrqBindError.BadMsixBar)
                  else
                    ok (core.result.Result.Err
                      irq.types.IrqBindError.BadMsixBar)
                else
                  ok (core.result.Result.Err irq.types.IrqBindError.BadMsixBar)
            else ok (core.result.Result.Err irq.types.IrqBindError.NoMsixCap)
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Unit (core.convert.FromSame irq.types.IrqBindError) residual

end nonos_irq
