/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

Machine-checked properties of the MSI-X interrupt-bind validator. Irq.lean is
generated by Charon and Aeneas from src/hardware/broker/irq/validate.rs, so the
`validate_msix_request` it defines IS the real kernel function lowered from the
MIR rustc compiles, not a retyped model. The theorems below are proven directly
on that extracted definition: a request that sets a flag bit the kernel does not
know is refused with UnsupportedFlags before any device state is consulted.

The extracted `validate_msix_request` calls `Option::ok_or` on the later
device-handle path, which Aeneas models as an opaque axiom; because that call is
in the function's definition, every theorem about it carries that one Aeneas
axiom in its closure alongside Lean's standard three, even a proof like this one
that returns before reaching it. It is a faithful stand-in for the core method,
not a `sorry`.
-/

import NonosExtraction.Irq

open Aeneas Aeneas.Std Result
open nonos_irq

namespace NonosExtraction.Irq

/-- A request carrying a flag bit outside the known set is refused before any
    device state is read: once the flag mask `fk` (`FLAGS_KNOWN`) is fixed, a
    non-zero `flags & !fk` yields UnsupportedFlags. Proven on the extracted
    control flow. -/
theorem unsupported_flags_rejected
    (req : irq.types.IrqBindRequest) (pool : Std.Usize)
    (handle : Option irq.validate.MsixHandleView) (grant : Bool)
    (fk : Std.U32) (hfk : irq.types.FLAGS_KNOWN = ok fk)
    (hbad : req.flags &&& (~~~ fk) ≠ 0#u32) :
    irq.validate.validate_msix_request req pool handle grant
      = ok (.Err irq.types.IrqBindError.UnsupportedFlags) := by
  have hcond : (req.flags &&& (~~~ fk) != 0#u32) = true := by
    simp only [bne_iff_ne, ne_eq]; exact hbad
  unfold irq.validate.validate_msix_request
  rw [hfk]
  simp only [lift, bind_tc_ok]
  rw [hcond]
  rfl

end NonosExtraction.Irq
