/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

Refinement proofs for the extracted user-copy range policy and the extracted
page-permission encoding. Policy/Funs.lean is generated by Charon and Aeneas
from src/usercopy/policy.rs and src/memory/paging/types/permissions, so the
theorems below are about the real kernel decision logic, lowered from its
own MIR. They prove the extracted check_range implements exactly the
acceptance predicate that Nonos.Isolation models (null, oversize, overflow,
and user-limit checks, with the exact error variant on every rejecting
path), and that the extracted PTE encoding preserves the W^X discipline:
present always set, writable exactly on WRITE, user exactly on USER, and NX
exactly on missing EXECUTE.
-/

import Policy.Funs
import Nonos.Isolation

open Aeneas Aeneas.Std Result
open nonos_policy

namespace NonosExtraction.PolicyProofs

/-! ## Shared bridges -/

private theorem uscalar_eq_val {ty} (x y : UScalar ty) : (x = y) ↔ (x.val = y.val) := by
  rw [UScalar.eq_equiv_bv_eq]
  exact BitVec.toNat_eq

private theorem nat_bridge_eq (n v k : Nat) (hv : v = 2 ^ k) :
    (decide (n &&& v = v)) = n.testBit k := by
  subst hv
  rw [Nat.and_two_pow]
  have hpos : 0 < 2 ^ k := Nat.two_pow_pos k
  cases h : n.testBit k <;> simp_all

private theorem shl32_1 : (1#u32 <<< 1#i32 : Result Std.U32) = ok 2#u32 := rfl
private theorem shl32_2 : (1#u32 <<< 2#i32 : Result Std.U32) = ok 4#u32 := rfl
private theorem shl32_3 : (1#u32 <<< 3#i32 : Result Std.U32) = ok 8#u32 := rfl
private theorem shl32_4 : (1#u32 <<< 4#i32 : Result Std.U32) = ok 16#u32 := rfl
private theorem shl32_5 : (1#u32 <<< 5#i32 : Result Std.U32) = ok 32#u32 := rfl
private theorem shl32_6 : (1#u32 <<< 6#i32 : Result Std.U32) = ok 64#u32 := rfl
private theorem shl64_0 : (1#u64 <<< 0#i32 : Result Std.U64) = ok 1#u64 := rfl
private theorem shl64_1 : (1#u64 <<< 1#i32 : Result Std.U64) = ok 2#u64 := rfl
private theorem shl64_2 : (1#u64 <<< 2#i32 : Result Std.U64) = ok 4#u64 := rfl
private theorem shl64_3 : (1#u64 <<< 3#i32 : Result Std.U64) = ok 8#u64 := rfl
private theorem shl64_4 : (1#u64 <<< 4#i32 : Result Std.U64) = ok 16#u64 := rfl
private theorem shl64_8 : (1#u64 <<< 8#i32 : Result Std.U64) = ok 256#u64 := rfl
private theorem shl64_63 :
    (1#u64 <<< 63#i32 : Result Std.U64) = ok 9223372036854775808#u64 := rfl

/-! ## The extracted W^X predicate -/

theorem is_wx_violation_spec (p : memory.paging.types.permissions.flags.PagePermissions) :
    is_wx_violation p = ok (p.bits.val.testBit 1 && p.bits.val.testBit 2) := by
  simp only [is_wx_violation,
    memory.paging.types.permissions.flags.PagePermissions.is_wx_violation,
    memory.paging.types.permissions.flags.PagePermissions.contains,
    memory.paging.types.permissions.flags.PagePermissions.WRITE,
    memory.paging.types.permissions.flags.PagePermissions.EXECUTE,
    memory.paging.constants.permissions.PERM_WRITE,
    memory.paging.constants.permissions.PERM_EXECUTE,
    lift, bind_tc_ok, shl32_1, shl32_2]
  simp only [uscalar_eq_val, UScalar.val_and]
  rw [nat_bridge_eq _ _ 1 (by decide), nat_bridge_eq _ _ 2 (by decide)]
  cases h1 : p.bits.val.testBit 1 <;> simp

/-- The extracted predicate agrees with the Nonos.Isolation model. -/
theorem is_wx_violation_iff (p : memory.paging.types.permissions.flags.PagePermissions) :
    is_wx_violation p = ok true ↔
      Nonos.Isolation.IsWxViolation
        { write := p.bits.val.testBit 1, execute := p.bits.val.testBit 2 } := by
  rw [is_wx_violation_spec]
  unfold Nonos.Isolation.IsWxViolation
  constructor
  · intro h
    have hb := (ok.injEq _ _).mp h
    constructor <;> simp_all
  · intro ⟨hw, hx⟩
    simp_all

/-! ## The extracted PTE encoding -/

set_option maxHeartbeats 64000000 in
/-- The extracted to_pte_flags never fails, and its output carries exactly
    the security bits the model demands: present set, writable iff WRITE,
    user iff USER, NX iff not EXECUTE. -/
theorem to_pte_flags_spec (p : memory.paging.types.permissions.flags.PagePermissions) :
    ∃ v, to_pte_flags p = ok v ∧
      v.val.testBit 0 = true ∧
      v.val.testBit 1 = p.bits.val.testBit 1 ∧
      v.val.testBit 2 = p.bits.val.testBit 3 ∧
      v.val.testBit 63 = !p.bits.val.testBit 2 := by
  simp only [to_pte_flags,
    memory.paging.types.permissions.convert.PagePermissions.to_pte_flags,
    memory.paging.types.permissions.flags.PagePermissions.contains,
    memory.paging.types.permissions.flags.PagePermissions.WRITE,
    memory.paging.types.permissions.flags.PagePermissions.USER,
    memory.paging.types.permissions.flags.PagePermissions.WRITE_THROUGH,
    memory.paging.types.permissions.flags.PagePermissions.NO_CACHE,
    memory.paging.types.permissions.flags.PagePermissions.GLOBAL,
    memory.paging.types.permissions.flags.PagePermissions.EXECUTE,
    memory.paging.constants.permissions.PERM_WRITE,
    memory.paging.constants.permissions.PERM_USER,
    memory.paging.constants.permissions.PERM_WRITE_THROUGH,
    memory.paging.constants.permissions.PERM_NO_CACHE,
    memory.paging.constants.permissions.PERM_GLOBAL,
    memory.paging.constants.permissions.PERM_EXECUTE,
    memory.paging.constants.pte_flags.PTE_PRESENT,
    memory.paging.constants.pte_flags.PTE_WRITABLE,
    memory.paging.constants.pte_flags.PTE_USER,
    memory.paging.constants.pte_flags.PTE_WRITE_THROUGH,
    memory.paging.constants.pte_flags.PTE_CACHE_DISABLE,
    memory.paging.constants.pte_flags.PTE_GLOBAL,
    memory.paging.constants.pte_flags.PTE_NO_EXECUTE,
    -- The PTE constants name the shared flag vocabulary at the paging
    -- boundary rather than restating its bit positions, so unfolding them
    -- lands on these and the encoding is only literal one step further down.
    arch.paging.descriptor.flags.PRESENT,
    arch.paging.descriptor.flags.WRITABLE,
    arch.paging.descriptor.flags.USER,
    arch.paging.descriptor.flags.WRITE_THROUGH,
    arch.paging.descriptor.flags.NO_CACHE,
    arch.paging.descriptor.flags.GLOBAL,
    arch.paging.descriptor.flags.NO_EXECUTE,
    lift, bind_tc_ok, shl32_1, shl32_2, shl32_3, shl32_4, shl32_5, shl32_6,
    shl64_0, shl64_1, shl64_2, shl64_3, shl64_4, shl64_8, shl64_63]
  simp only [uscalar_eq_val, UScalar.val_and]
  rw [nat_bridge_eq _ _ 1 (by decide), nat_bridge_eq _ _ 3 (by decide),
    nat_bridge_eq _ _ 6 (by decide), nat_bridge_eq _ _ 5 (by decide),
    nat_bridge_eq _ _ 4 (by decide), nat_bridge_eq _ _ 2 (by decide)]
  cases h1 : p.bits.val.testBit 1 <;> cases h2 : p.bits.val.testBit 3 <;>
    cases h3 : p.bits.val.testBit 6 <;> cases h4 : p.bits.val.testBit 5 <;>
    cases h5 : p.bits.val.testBit 4 <;> cases h6 : p.bits.val.testBit 2 <;>
    exact ⟨_, rfl, by decide, by decide, by decide, by decide⟩

/-- The W^X page theorem on the extracted encoder: a permission set that is
    not a violation never encodes a page both writable and executable. -/
theorem extracted_no_wx_page (p : memory.paging.types.permissions.flags.PagePermissions)
    (v : Std.U64) (hv : to_pte_flags p = ok v)
    (hok : ¬(p.bits.val.testBit 1 = true ∧ p.bits.val.testBit 2 = true)) :
    ¬(v.val.testBit 1 = true ∧ v.val.testBit 63 = false) := by
  obtain ⟨v', hv', _, hw, _, hx⟩ := to_pte_flags_spec p
  rw [hv] at hv'
  have heq : v = v' := (ok.injEq _ _).mp hv'
  subst heq
  intro ⟨h1, h63⟩
  rw [hw] at h1
  rw [hx] at h63
  apply hok
  constructor
  · exact h1
  · cases h : p.bits.val.testBit 2
    · rw [h] at h63
      simp at h63
    · rfl

/-! ## The extracted user-copy range policy -/

private theorem max_copy_val :
    ∃ m, usercopy.policy.MAX_COPY_SIZE = ok m ∧ m.val = 67108864 := by
  unfold usercopy.policy.MAX_COPY_SIZE
  have hm1 : (64#usize * 1024#usize : Result Std.Usize) = (64#usize).mul 1024#usize := rfl
  have h1 := UScalar.mul_equiv 64#usize 1024#usize
  rcases he1 : (64#usize).mul 1024#usize with z1 | e1 | _ <;> rw [he1] at h1
  · have hz1 : z1.val = 65536 := by
      simp at h1
      omega
    have hm2 : (z1 * 1024#usize : Result Std.Usize) = z1.mul 1024#usize := rfl
    have h2 := UScalar.mul_equiv z1 1024#usize
    rcases he2 : z1.mul 1024#usize with z2 | e2 | _ <;> rw [he2] at h2
    · refine ⟨z2, by simp [hm1, he1, hm2, he2], ?_⟩
      simp [hz1] at h2
      omega
    · simp [hz1] at h2
      scalar_tac
    · exact absurd h2 (by simp)
  · simp at h1
    scalar_tac
  · exact absurd h1 (by simp)

set_option maxHeartbeats 64000000 in
/-- The extracted check_range never fails, and it accepts a non-empty copy
    exactly on the model's condition: non-null, within the copy bound, and
    the last byte inside user space without wrapping. -/
theorem check_range_spec (addr : Std.U64) (len : Std.Usize) :
    ∃ v, usercopy.policy.check_range addr len = ok v ∧
      ((∃ r, v = core.result.Result.Ok (some r)) ↔
        (addr.val ≠ 0 ∧ len.val ≠ 0 ∧ len.val ≤ 67108864 ∧
          addr.val + (len.val - 1) ≤ 140737488355327)) := by
  obtain ⟨m, hm, hmval⟩ := max_copy_val
  unfold usercopy.policy.check_range
  rw [hm]
  by_cases h0 : addr = 0#u64
  · rw [if_pos h0]
    have h0v : addr.val = 0 := by
      rw [uscalar_eq_val] at h0
      simpa using h0
    exact ⟨_, rfl, iff_of_false (by rintro ⟨r, hr⟩; cases hr)
      (by intro h; exact h.1 h0v)⟩
  · rw [if_neg h0]
    have h0v : addr.val ≠ 0 := by
      rw [uscalar_eq_val] at h0
      simpa using h0
    simp only [bind_tc_ok]
    by_cases hbig : len > m
    · rw [if_pos hbig]
      have hbigv : 67108864 < len.val := by
        simp only [gt_iff_lt, UScalar.lt_equiv] at hbig
        omega
      exact ⟨_, rfl, iff_of_false (by rintro ⟨r, hr⟩; cases hr)
        (by intro h; omega)⟩
    · rw [if_neg hbig]
      have hsmall : len.val ≤ 67108864 := by
        simp only [gt_iff_lt, UScalar.lt_equiv] at hbig
        omega
      by_cases hz : len = 0#usize
      · rw [if_pos hz]
        have hzv : len.val = 0 := by
          rw [uscalar_eq_val] at hz
          simpa using hz
        exact ⟨_, rfl, iff_of_false (by rintro ⟨r, hr⟩; simp at hr)
          (by intro h; exact h.2.1 hzv)⟩
      · rw [if_neg hz]
        have hzv : len.val ≠ 0 := by
          rw [uscalar_eq_val] at hz
          simpa using hz
        simp only [lift, bind_tc_ok]
        have hcast : (UScalar.cast .U64 len : Std.U64).val = len.val := by simp
        have hsub := UScalar.sub_equiv (UScalar.cast .U64 len : Std.U64) 1#u64
        rcases hse : ((UScalar.cast .U64 len : Std.U64) - 1#u64 : Result Std.U64)
          with d | e | _ <;> rw [hse] at hsub
        · have hdval : d.val = len.val - 1 := by
            simp [hcast] at hsub
            omega
          simp only [bind_tc_ok]
          have hadd := U64.checked_add_bv_spec addr d
          rcases hae : addr.checked_add d with _ | s <;> rw [hae] at hadd
          · -- The addition wrapped: the sum exceeds every user address.
            have hover : U64.max < addr.val + d.val := hadd
            have hmax : U64.max = 18446744073709551615 := by scalar_tac
            simp only [core.option.Option.ok_or, bind_tc_ok,
              core.result.Result.Insts.CoreOpsTry.branch,
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual,
              core.convert.FromSame.from, bind_tc_ok]
            exact ⟨_, rfl, iff_of_false (by rintro ⟨r, hr⟩; cases hr)
              (by intro h; omega)⟩
          · -- The addition fits in a u64.
            obtain ⟨hsum_le, hsval, _⟩ := hadd
            simp only [core.option.Option.ok_or, bind_tc_ok,
              core.result.Result.Insts.CoreOpsTry.branch]
            by_cases hlim : s > usercopy.policy.USER_SPACE_END
            · rw [if_pos hlim]
              have hlimv : 140737488355327 < s.val := by
                simp only [gt_iff_lt, UScalar.lt_equiv] at hlim
                simpa [usercopy.policy.USER_SPACE_END] using hlim
              exact ⟨_, rfl, iff_of_false (by rintro ⟨r, hr⟩; cases hr)
                (by intro h; omega)⟩
            · rw [if_neg hlim]
              have hlimv : s.val ≤ 140737488355327 := by
                simp only [gt_iff_lt, UScalar.lt_equiv, Nat.not_lt] at hlim
                simpa [usercopy.policy.USER_SPACE_END] using hlim
              exact ⟨_, rfl, iff_of_true ⟨_, rfl⟩ ⟨h0v, hzv, hsmall, by omega⟩⟩
        · -- The subtraction cannot fail: len is nonzero.
          exfalso
          rw [hcast] at hsub
          simp at hsub
          omega
        · exact absurd hsub (by simp)

/-- Corollary in the model's vocabulary: acceptance of a non-empty copy is
    exactly Nonos.Isolation.Accepts. -/
theorem check_range_accepts_iff (addr : Std.U64) (len : Std.Usize) (hlen : len.val ≠ 0) :
    (∃ v r, usercopy.policy.check_range addr len = ok v ∧
      v = core.result.Result.Ok (some r)) ↔
      Nonos.Isolation.Accepts addr.val len.val := by
  obtain ⟨v, hv, hiff⟩ := check_range_spec addr len
  unfold Nonos.Isolation.Accepts Nonos.Isolation.maxCopy Nonos.Isolation.userEnd
  constructor
  · intro ⟨v', r, hv', hr⟩
    rw [hv] at hv'
    have : v = v' := (ok.injEq _ _).mp hv'
    subst this
    have := hiff.mp ⟨r, hr⟩
    omega
  · intro h
    have hex := hiff.mpr (by omega)
    obtain ⟨r, hr⟩ := hex
    exact ⟨v, r, hv, hr⟩

end NonosExtraction.PolicyProofs
