/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

The machine-checked refinement. Caps.lean is generated by Charon and Aeneas
from the kernel's src/capabilities/bits.rs, so its definitions ARE the real
Rust, lowered from the same MIR rustc compiles. The theorems below prove
those extracted definitions compute exactly the semantics the hand-written
specification layer reasons about: capsOf and Grants from Nonos.Capability
and Nonos.CapabilityBits. Together with the lattice theorems proven over
that specification, every abstract security property now holds of the
extracted-from-real-Rust code by transitivity, with no retyped model in
between.
-/

import NonosExtraction.Caps
import Nonos.Capability
import Nonos.CapabilityBits

open Aeneas Aeneas.Std Result
open Nonos.Capability (Grants grant revoke attenuate)
open Nonos.CapabilityBits (capsOf bitOf mask64 not64)
open nonos_caps

namespace NonosExtraction

/-- The bit index each capability occupies in the kernel token word,
    matching the `bit` table in src/capabilities/types/bit.rs. -/
def idx : capabilities.types.defs.Capability → Nat
  | .CoreExec => 0
  | .IO => 1
  | .Network => 2
  | .IPC => 3
  | .Memory => 4
  | .Crypto => 5
  | .FileSystem => 6
  | .Hardware => 7
  | .Debug => 8
  | .Admin => 9
  | .RegisterService => 10
  | .GraphicsDisplayQuery => 11
  | .GraphicsSurfaceCreate => 12
  | .GraphicsSurfaceMap => 13
  | .GraphicsPresent => 14
  | .DeviceEnum => 15
  | .Driver => 16
  | .Mmio => 17
  | .Irq => 18
  | .Dma => 19
  | .Pio => 20
  | .InputSource => 21
  | .TimeSet => 22
  | .SpawnBroker => 23
  | .SpawnWindow => 24
  | .ProcessControl => 25
  | .StoreWrite => 26
  | .EnrolDevRoot => 27
  | .Keyring => 28
  | .Entropy => 29
  | .AppInstall => 30

theorem idx_lt_64 (cap : capabilities.types.defs.Capability) : idx cap < 64 := by
  cases cap <;> decide

private theorem u64_ne_zero (x : Std.U64) : (x != 0#u64) = decide (x.val ≠ 0) := by
  simp [bne, BEq.beq, BitVec.toNat_eq]

private theorem nat_bridge (n k : Nat) : (decide (n &&& 2 ^ k ≠ 0)) = n.testBit k := by
  rw [Nat.and_two_pow]
  cases h : n.testBit k <;> simp

private theorem nat_bridge2 (n v k : Nat) (hv : v = 2 ^ k) :
    (decide (n &&& v ≠ 0)) = n.testBit k := by
  subst hv
  exact nat_bridge n k

/-- The extracted bit table is total and yields exactly one bit: the power of
    two at the capability's index. -/
theorem bit_spec (cap : capabilities.types.defs.Capability) :
    ∃ v, capabilities.types.bit.Capability.bit cap = ok v ∧ v.val = 2 ^ idx cap := by
  cases cap <;> exact ⟨_, rfl, by decide⟩

/-- A single test never fails, and answers exactly the denotation: the
    extracted has_capability IS the Grants semantics of the token word. -/
theorem has_capability_spec (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
    capabilities.bits.has_capability bits cap = ok (capsOf bits.val (idx cap)) := by
  cases cap <;> (
    simp only [capabilities.bits.has_capability, capabilities.types.bit.Capability.bit,
      lift, bind_tc_ok, ok.injEq, Nonos.CapabilityBits.capsOf, idx]
    rw [u64_ne_zero]
    simp only [UScalar.val_and]
    exact nat_bridge2 bits.val _ _ (by decide))

/-- Corollary in the vocabulary of the lattice theorems: the extracted test
    accepts exactly when the abstract token grants the capability. -/
theorem has_capability_iff_grants (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
    capabilities.bits.has_capability bits cap = ok true ↔
      Grants (capsOf bits.val) (idx cap) := by
  rw [has_capability_spec]
  unfold Nonos.Capability.Grants
  constructor
  · intro h
    exact (ok.injEq _ _).mp h
  · intro h
    rw [h]

/-- The extracted add never fails and computes the word-level grant. -/
theorem add_capability_spec (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
    ∃ r, capabilities.bits.add_capability bits cap = ok r ∧
      r.val = bits.val ||| bitOf (idx cap) := by
  cases cap <;>
    exact ⟨_, rfl, by simp [Nonos.CapabilityBits.bitOf, idx, Nat.shiftLeft_eq]⟩

/-- Semantic corollary: the token produced by the extracted add grants
    exactly what the abstract grant does, for every capability id. -/
theorem add_capability_grants (bits : Std.U64) (cap : capabilities.types.defs.Capability)
    (r : Std.U64) (h : capabilities.bits.add_capability bits cap = ok r) (x : Nat) :
    Grants (capsOf r.val) x ↔ Grants (grant (capsOf bits.val) (idx cap)) x := by
  obtain ⟨r', hr', hval⟩ := add_capability_spec bits cap
  rw [h] at hr'
  have heq : r = r' := (ok.injEq _ _).mp hr'
  subst heq
  rw [← Nonos.CapabilityBits.lor_denotes_grant]
  unfold Nonos.Capability.Grants Nonos.CapabilityBits.capsOf
  rw [hval]

/-- The extracted remove never fails and computes the word-level revoke:
    the 64-bit complement of the single bit, ANDed in. -/
theorem remove_capability_spec (bits : Std.U64) (cap : capabilities.types.defs.Capability) :
    ∃ r, capabilities.bits.remove_capability bits cap = ok r ∧
      r.val = bits.val &&& not64 (bitOf (idx cap)) := by
  cases cap <;>
    exact ⟨_, rfl, by
      simp [Nonos.CapabilityBits.not64, Nonos.CapabilityBits.mask64,
        Nonos.CapabilityBits.bitOf, idx, Nat.shiftLeft_eq]
      congr 1⟩

/-- Semantic corollary: the token produced by the extracted remove grants
    exactly what the abstract revoke does, for every capability id. -/
theorem remove_capability_revokes (bits : Std.U64) (cap : capabilities.types.defs.Capability)
    (r : Std.U64) (h : capabilities.bits.remove_capability bits cap = ok r) (x : Nat) :
    Grants (capsOf r.val) x ↔ Grants (revoke (capsOf bits.val) (idx cap)) x := by
  obtain ⟨r', hr', hval⟩ := remove_capability_spec bits cap
  rw [h] at hr'
  have heq : r = r' := (ok.injEq _ _).mp hr'
  subst heq
  rw [← Nonos.CapabilityBits.land_not_denotes_revoke bits.val (idx cap) x
    bits.bv.isLt (idx_lt_64 cap)]
  unfold Nonos.Capability.Grants Nonos.CapabilityBits.capsOf
  rw [hval]

/-- The confinement chain, landed on the extracted code: a token built by the
    extracted remove never grants a capability the original token lacked. -/
theorem extracted_remove_confines (bits : Std.U64) (cap : capabilities.types.defs.Capability)
    (r : Std.U64) (h : capabilities.bits.remove_capability bits cap = ok r) (x : Nat)
    (hg : Grants (capsOf r.val) x) : Grants (capsOf bits.val) x := by
  have hrev := (remove_capability_revokes bits cap r h x).mp hg
  exact Nonos.Capability.revoke_leq (capsOf bits.val) (idx cap) x hrev

end NonosExtraction
