[package]
name = "nonos_capsule_setup_wizard"
version = "0.3.0"
edition = "2021"
publish = false

[[bin]]
name = "setup_wizard"
path = "src/main.rs"

[dependencies]
nonos_libc = { package = "nonos_userland_libc", path = "../libc" }
nonos_toolkit = { package = "nonos_toolkit", path = "../toolkit" }
nonos_policy_proto = { path = "../policy_proto" }

[features]
default = []
