// NONOS Operating System
// Copyright (C) 2026 NONOS Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

//! The installed command-line tools shown in the Launchpad, generated by
//! `tools/nonos-app` from `userland/apps.list`. Each tile launches the tool
//! capsule by its service. Do not edit by hand: run `nonos-app add <crate>`.

/// One installed tool: the name on its tile and the service it launches under.
pub struct ToolApp {
    pub label: &'static [u8],
    pub service: &'static [u8],
}

/// Every installed tool, generated from `userland/apps.list`.
pub const TOOL_APPS: [ToolApp; 7] = [
    ToolApp { label: b"grex", service: b"tool.grex" },
    ToolApp { label: b"dotenv-linter", service: b"tool.dotenv-linter" },
    ToolApp { label: b"pastel", service: b"tool.pastel" },
    ToolApp { label: b"jsonxf", service: b"tool.jsonxf" },
    ToolApp { label: b"tokei", service: b"tool.tokei" },
    ToolApp { label: b"huniq", service: b"tool.huniq" },
    ToolApp { label: b"csview", service: b"tool.csview" },
];
