# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# grex: unmodified crates.io source cross-compiled for x86_64-nonos and
# installed as a signed, STARK-attested capsule. Generated by tools/nonos-app.

CAPSULE_SLUG               := grex
CAPSULE_HANDLE             := grex
CAPSULE_DIR                := userland/capsule_grex
CAPSULE_BIN_NAME           := grex
CAPSULE_DOMAIN             := crates.io
CAPSULE_NAMESPACE          := systems.nonos.tool.grex
CAPSULE_SERVICE_ENDPOINT   := service:4900:tool.grex
CAPSULE_REPLY_ENDPOINT     := reply:4901:endpoint.tool.grex.reply
CAPSULE_REQUIRED_CAPS      := 0x19
CAPSULE_CAPS_CEILING       := 0x19
CAPSULE_PREBUILT_BIN       := target/upstream-grex/bin/grex
CAPSULE_METADATA           := crates.io grex publisher

include nonos-mk/capsule.mk
